import {createClient,unwrap,ExtensionError,type HostContext,type Project} from '@ambleloft/extension-sdk/webview';
const strings={
 en:{title:'Project Card',subtitle:'A little context. A clearer start.',choose:'Choose a Project',change:'Change Project',empty:'Your project, at a glance',intro:'Choose a local project to view its name and description here.',note:'You choose what to share. Your working directory stays private.',refresh:'Refresh',cancel:'Cancel',loading:'Reading project…',noDescription:'No description yet.',id:'Project ID',retry:'Try Again',unavailable:'Open this extension inside Ambleloft to get started.',failed:'The project could not be loaded. Check its permissions and try again.',unknown:'The result could not be confirmed. Check the project before trying again.',ready:'Project updated'},
 zh:{title:'项目卡片',subtitle:'了解项目，从这里开始。',choose:'选择项目',change:'切换项目',empty:'项目概况，一目了然',intro:'选择一个本地项目，在这里查看它的名称与说明。',note:'由你决定分享什么，工作目录始终保持私密。',refresh:'刷新',cancel:'取消',loading:'正在读取项目…',noDescription:'这个项目还没有说明。',id:'项目 ID',retry:'重试',unavailable:'请在 Ambleloft 中打开此扩展。',failed:'暂时无法读取项目，请检查授权后重试。',unknown:'暂时无法确认结果，请先检查项目再重试。',ready:'项目已更新'}
};
let messages=strings.zh,project:Project|null=null,controller:AbortController|null=null,busy=false,connected=false;
const element=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const choose=element<HTMLButtonElement>('choose'),refresh=element<HTMLButtonElement>('refresh'),cancel=element<HTMLButtonElement>('cancel'),status=element('status');
function localize(context:HostContext){messages=context.locale.toLowerCase().startsWith('zh')?strings.zh:strings.en;document.documentElement.lang=messages===strings.zh?'zh-CN':'en';document.documentElement.dataset.theme=context.theme;document.title=messages.title;for(const el of document.querySelectorAll<HTMLElement>('[data-message]'))el.textContent=messages[el.dataset.message as keyof typeof messages];render();}
function render(){choose.textContent=project?messages.change:messages.choose;choose.disabled=busy||!connected;refresh.disabled=busy;refresh.hidden=!project;cancel.hidden=!busy||!controller;element('empty').hidden=!!project;element('card').hidden=!project;if(project){element('project-name').textContent=project.name;element('project-description').textContent=project.description||messages.noDescription;element('project-id').textContent=project.id;}}
function report(error:unknown){if(error instanceof ExtensionError&&error.code==='CANCELLED'){status.textContent='';return;}status.textContent=error instanceof ExtensionError&&error.effectStatus==='unknown'?messages.unknown:messages.failed;}
async function read(){if(!project)return;controller=new AbortController();busy=true;status.textContent=messages.loading;render();try{const value=unwrap(await client.invoke('example.project-card.describe',{projectId:project.id},{signal:controller.signal}));project={id:String(value.id),name:String(value.name),description:String(value.description)};status.textContent=messages.ready;}catch(error){report(error);}finally{controller=null;busy=false;render();}}
let client:ReturnType<typeof createClient>;
async function start(){try{client=createClient();localize(await client.initialize());connected=true;const subscription=client.onHostContextChanged(localize);window.addEventListener('pagehide',()=>{controller?.abort();subscription.dispose();},{once:true});render();}catch{status.textContent=messages.unavailable;render();}}
choose.addEventListener('click',async()=>{busy=true;status.textContent='';render();try{const selected=unwrap(await client.selectProject({capabilities:['projects.read']}));if(selected){project=selected;await read();}}catch(error){report(error);}finally{busy=false;render();}});
refresh.addEventListener('click',()=>void read());cancel.addEventListener('click',()=>controller?.abort());void start();
