import {test,expect} from '@playwright/test';
test('operation confirmation preserves explicit consent, remember scope and error recovery',async({page})=>{
 await page.addInitScript(()=>{(window as any).desktop={getProvider:async()=>({configured:false}),getDevice:async()=>({mode:'desktop'}),readWorkspace:async()=>({projects:[],tasks:[],theme:'light'}),listRuns:async()=>[],onRun:()=>()=>{},onCommand:()=>()=>{},extensionPage:{context:async()=>{},overlay:()=>{},onInteraction:(callback:any)=>{(window as any).__interaction=callback;return()=>{};},onInteractionClose:()=>()=>{},respond:async(input:any)=>{(window as any).__response=input;if((window as any).__fail)throw Error('暂时无法确认，请重试');}}};});
 await page.goto('/');await page.waitForFunction(()=>!!(window as any).__interaction);
 const open=async(allowRemember=true)=>page.evaluate(allowRemember=>(window as any).__interaction({id:'op',kind:'operation',extensionName:'项目助手',title:'创建项目回顾草稿',description:'根据项目资料整理一份回顾，保存到当前项目。',project:'品牌设计',caller:'agent',capabilities:['projects.read','conversations.create'],input:{title:'项目回顾'},allowRemember,impact:['bulk']}),allowRemember);
 await open();const dialog=page.getByRole('dialog',{name:'确认扩展操作'});
 await expect(dialog.getByRole('heading',{name:'创建项目回顾草稿'})).toBeVisible();await expect(dialog.getByRole('checkbox')).not.toBeChecked();await expect(dialog.locator('pre')).not.toBeVisible();
 await page.screenshot({path:'test-results/operation-dialog.png',animations:'disabled'});
 await dialog.getByRole('checkbox').check();await page.evaluate(()=>{(window as any).__fail=true;});await dialog.getByRole('button',{name:'确认执行'}).click();await expect(dialog.getByRole('alert').filter({hasText:'暂时无法确认'})).toBeVisible();await expect(dialog.getByRole('checkbox')).toBeChecked();
 await page.evaluate(()=>{(window as any).__fail=false;});await dialog.getByRole('button',{name:'确认执行'}).click();expect(await page.evaluate(()=>(window as any).__response)).toMatchObject({id:'op',cancel:false,remember:true});await expect(dialog).toHaveCount(0);
 await open(false);await expect(dialog.getByRole('checkbox')).toHaveCount(0);await page.setViewportSize({width:640,height:720});await page.evaluate(()=>{document.documentElement.dataset.theme='dark';});await page.screenshot({path:'test-results/operation-dialog-dark.png',animations:'disabled'});expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await dialog.getByRole('button',{name:'取消',exact:true}).click();expect(await page.evaluate(()=>(window as any).__response)).toMatchObject({cancel:true,remember:false});
});
