import {test,expect} from '@playwright/test';
async function setup(page:import('@playwright/test').Page){await page.addInitScript(()=>{let listener=()=>{},authListener=()=>{};const preferences={receive:true,muted:false};let items=[{id:'a',eventKey:'a',source:'host',title:'项目邀请',body:'欢迎加入项目',category:'actionRequired',businessState:'pending',validity:'active',severity:'info',readAt:null,dismissedAt:null,receivedAt:100,actions:[]},{id:'b',eventKey:'b',source:'host',title:'报告已完成',body:'可以查看报告了',category:'notice',businessState:null,validity:'active',severity:'info',readAt:100,dismissedAt:null,receivedAt:200,actions:[]}];let catalog:any={revision:0,defaultId:null,connections:[]};const match=(i:any,p:any)=>!p?.filter||p.filter==='all'||p.filter==='unread'&&i.readAt===null||p.filter==='pending'&&i.businessState==='pending';const api={list:async(p:any)=>({items:items.filter(i=>match(i,p)),unread:items.filter(i=>i.readAt===null).length}),sources:async()=>[{id:'host',name:'Agent',installed:true,preferences}],onChanged:(cb:any)=>{const old=listener;listener=()=>{old();cb();};return()=>{};},markRead:async({id}:any)=>{const i=items.find(i=>i.id===id)!;i.readAt=500;listener();return {...i};},dismiss:async({id}:any)=>{items=items.filter(i=>i.id!==id);listener();},bulk:async(p:any)=>{let count=0;items=items.filter(i=>{if(!match(i,p))return true;if(p.action==='read'&&i.readAt===null){i.readAt=500;count++;}if(p.action==='clearRead'&&i.readAt!==null&&i.businessState!=='pending'){count++;return false;}return true;});listener();return {count};},setPreferences:async(p:any)=>{Object.assign(preferences,p.preferences);listener();return preferences;}};
(window as any).desktop={getProvider:async()=>({configured:false}),getDevice:async()=>({mode:'desktop'}),readWorkspace:async()=>({tasks:[],projects:[],theme:'light',language:'zh-CN'}),listRuns:async()=>[],onRun:()=>()=>{},onCommand:()=>()=>{},messages:api,authentication:{onChanged:(cb:any)=>{authListener=cb;return()=>{};},connections:async(p:any)=>{if(!p||p.action==='list')return structuredClone(catalog);if(p.action==='save')catalog.connections.push({...p.value,id:'company'});if(p.action==='default')catalog.defaultId=p.id;catalog.revision++;authListener();return structuredClone(catalog);}}};});await page.goto('/');}
test('messages do not read on list open; filtered bulk clear preserves pending items',async({page})=>{await setup(page);await page.getByRole('button',{name:/消息中心/}).click();await expect(page.locator('.message-row')).toHaveCount(2);await expect(page.locator('.message-row.unread')).toHaveCount(1);await page.getByRole('button',{name:/清除已读/}).click();await expect(page.locator('.message-row')).toHaveCount(1);await page.getByRole('button',{name:/全部已读/}).click();await expect(page.locator('.message-row.unread')).toHaveCount(0);await expect(page.getByRole('button',{name:/清除已读/})).toBeDisabled();await page.locator('.message-open').click();await expect(page.getByRole('region',{name:'消息详情'})).toContainText('欢迎加入项目');await page.screenshot({path:'test-results/messages.png'});});
test('notification preferences and enterprise config forms are accessible',async({page})=>{await setup(page);await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'通知',exact:true}).click();await page.getByRole('switch',{name:'Agent 接收消息'}).uncheck();await expect(page.getByRole('switch',{name:'Agent 静音'})).toBeDisabled();await page.getByRole('button',{name:'账号',exact:true}).click();await page.getByRole('button',{name:'添加认证配置'}).click();await page.getByLabel('配置名称').fill('A 公司');await page.getByLabel('认证服务地址（Issuer URL）').fill('https://login.example.com');await page.getByLabel('客户端 ID（Client ID）').fill('desktop-client');await page.getByRole('button',{name:'保存配置'}).click();await expect(page.getByRole('heading',{name:'A 公司'})).toBeVisible();await page.getByRole('button',{name:'设为默认',exact:true}).click();await expect(page.getByText('默认配置',{exact:true})).toBeVisible();await page.screenshot({path:'test-results/accounts.png'});});
test('message filters preserve detail after reading and reflow in a narrow dark viewport',async({page})=>{
 await setup(page);await page.getByRole('button',{name:/消息中心/}).click();await page.getByRole('tab',{name:'未读',exact:true}).click();await expect(page.locator('.message-row')).toHaveCount(1);await page.locator('.message-open').click();await expect(page.locator('.message-row')).toHaveCount(0);await expect(page.getByRole('region',{name:'消息详情'})).toContainText('项目邀请');await page.getByRole('button',{name:'关闭详情'}).click();await expect(page.getByText('暂时没有消息')).toBeVisible();await page.getByRole('tab',{name:'待处理',exact:true}).click();await expect(page.locator('.message-row')).toHaveCount(1);await page.locator('.message-open').click();await page.setViewportSize({width:720,height:900});await page.evaluate(()=>{document.documentElement.dataset.theme='dark';});expect(await page.locator('.message-center').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await page.screenshot({path:'test-results/messages-narrow-dark.png',animations:'disabled'});
});
test('account draft survives cancelled navigation and discards only after confirmation',async({page})=>{
 await setup(page);await page.getByRole('button',{name:'设置',exact:true}).click();const nav=page.getByRole('navigation',{name:'设置导航'});await nav.getByRole('button',{name:'账号',exact:true}).click();await page.getByRole('button',{name:'添加认证配置'}).click();await page.getByLabel('配置名称').fill('未保存连接');await nav.getByRole('button',{name:'通用',exact:true}).click();await page.getByRole('button',{name:'继续编辑'}).click();await expect(page.getByLabel('配置名称')).toHaveValue('未保存连接');await nav.getByRole('button',{name:'通用',exact:true}).click();await page.getByRole('button',{name:'放弃修改'}).click();await expect(page.getByRole('heading',{name:'舒服地，开始工作'})).toBeVisible();await page.getByLabel('字体大小',{exact:true}).selectOption('120');await page.screenshot({path:'test-results/settings-general-updated.png',animations:'disabled'});
});
test('message action submits only identifiers and unknown results block repeat clicks',async({page})=>{
 await setup(page);await page.evaluate(()=>{const api=(window as any).desktop.messages;const message={id:'action-message',eventKey:'action',source:'host',title:'审批任务',body:'请确认报销申请',category:'actionRequired',businessState:'pending',validity:'active',severity:'info',revision:7,readAt:null,dismissedAt:null,receivedAt:100,actions:[{id:'approve',label:'同意申请',commandId:'demo.approve',effect:'write'}],executions:[] as any[]};api.list=async()=>({items:[message],unread:0});api.markRead=async()=>message;api.execute=async(input:any)=>{(window as any).__submitted=input;message.executions=[{id:'invocation',actionId:'approve',effect:'write',state:'unknown'}];return {ok:true};};});
 await page.getByRole('button',{name:/消息中心/}).click();await page.locator('.message-open').click();await page.getByRole('button',{name:'同意申请',exact:true}).click();expect(await page.evaluate(()=>(window as any).__submitted)).toEqual({messageId:'action-message',actionId:'approve',expectedRevision:7});await expect(page.getByRole('button',{name:'同意申请',exact:true})).toBeDisabled();await expect(page.getByRole('status')).toContainText('为避免重复提交');await page.screenshot({path:'test-results/message-action-unknown.png'});
});
