import { test, expect } from '@playwright/test';
test('projects organize drafts, preview details, edit and detach safely',async({page})=>{
 await page.goto('/');
 await expect(page.getByText('最近的任务',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'添加项目',exact:true}).click();
 await page.getByRole('textbox',{name:'项目名称',exact:true}).fill('品牌设计');
 await page.getByRole('textbox',{name:'项目说明',exact:true}).fill('品牌视觉与包装方案');
 await page.getByRole('textbox',{name:'工作目录',exact:true}).fill('/tmp/brand');
 await page.getByRole('button',{name:'保存项目',exact:true}).click();
 await expect(page.getByRole('heading',{name:'品牌设计',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'在项目中新建任务：品牌设计',exact:true}).click();
 await expect(page.getByLabel('当前项目')).not.toHaveValue('');
 await page.getByRole('textbox',{name:'任务内容'}).fill('设计包装');
 await page.getByRole('button',{name:'保存任务草稿'}).click();
 await page.getByRole('button',{name:'关闭',exact:true}).click();
 await expect(page.locator('.project-children .tree-task')).toContainText('设计包装');
 await page.locator('.project-tree-name').hover();
 await expect(page.getByRole('region',{name:'项目信息'})).toContainText('品牌设计');
 await expect(page.getByRole('region',{name:'项目信息'})).toContainText('1 个任务');
 await page.getByRole('region',{name:'项目信息'}).getByRole('button',{name:'编辑项目'}).click();
 await expect(page.getByRole('textbox',{name:'项目名称'})).toHaveValue('品牌设计');
 await page.getByRole('button',{name:'关闭',exact:true}).click();
 await page.getByRole('button',{name:'我的项目',exact:true}).click();
 await expect(page.locator('.project-tree')).toBeHidden();
 await expect(page.getByRole('button',{name:'添加项目',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'我的项目',exact:true}).click();
 await expect(page.locator('.project-tree')).toBeVisible();

 await page.locator('.new-task').click();
 await expect(page.getByLabel('当前项目')).toHaveValue('');
 await page.getByRole('button',{name:'管理任务：设计包装'}).click();
 await page.getByRole('textbox',{name:'任务名称'}).fill('包装方案');
 await page.getByLabel('所属项目').selectOption('');
 await page.getByRole('button',{name:'保存修改'}).click();
 await expect(page.getByRole('region',{name:'聊天',exact:true})).toContainText('包装方案');
 await page.getByRole('button',{name:'聊天',exact:true}).click();
 await expect(page.locator('#nav-chats')).toBeHidden();
 await page.getByRole('button',{name:'聊天',exact:true}).click();
 await expect(page.locator('#nav-chats')).toBeVisible();

 await page.getByRole('button',{name:'管理任务：包装方案'}).click();
 await page.getByLabel('所属项目').selectOption({label:'品牌设计'});
 await page.getByRole('button',{name:'保存修改'}).click();
 await page.getByRole('button',{name:'管理项目：品牌设计'}).click();
 await page.getByRole('button',{name:'删除项目',exact:true}).click();
 await expect(page.getByRole('dialog')).toContainText('不会删除本机文件');
 await page.getByRole('button',{name:'确认删除项目',exact:true}).click();
 await expect(page.locator('.project-tree')).toHaveCount(0);
 await expect(page.getByRole('region',{name:'聊天',exact:true})).toContainText('包装方案');
 await page.reload();await expect(page.getByRole('region',{name:'聊天',exact:true})).toContainText('包装方案');
 await page.screenshot({path:'test-results/sidebar-new.png'});
});
