const test=require('node:test'),assert=require('node:assert/strict');const {OperationRouter}=require('../core/extensions/operations.cjs');
function fixture(overrides={}){let dispatched=0,confirmed=0;const settings=new Map();const op={id:'test.ext.run',title:'Run',description:'test',handler:'run',exposeTo:['page','agent'],effect:'write',projectScoped:true,inputSchema:{},outputSchema:{},requiredPermissions:['projects.read'],...overrides};const item={id:'test.ext',kind:'package',enabled:true,trusted:true,active:'digest',generation:1,manifest:{operations:[op]}};const service={items:[item],database:{async call(method,p){if(method==='readSetting')return settings.get(p.key);settings.set(p.key,p.value);}},localized:(_i,s)=>s,displayName:()=> 'Test',check:async(c,cap,id)=>{if(c.generation!==item.generation||id!=='p')throw Object.assign(Error('FORBIDDEN'),{code:'FORBIDDEN'});},packages:{validateValue:async(_schema,value)=>!!value&&typeof value==='object'&&!Array.isArray(value)},hosts:{entries:new Map(),async invoke(_id,_op,input,options){await options.guard();options.onDispatch();dispatched++;return {done:true};}}};const router=new OperationRouter({service,workspace:{read:async()=>({projects:[{id:'p',name:'Project'}]})},confirm:async()=>{confirmed++;return {remember:true};}});const context={caller:'page',extensionId:item.id};return {router,service,item,op,context,counts:()=>({dispatched,confirmed})};}
test('write confirmation, read bypass and page-only exposure are enforced at router',async()=>{const f=fixture();assert.equal((await f.router.invoke(f.op.id,{projectId:'p'},f.context)).ok,true);assert.deepEqual(f.counts(),{dispatched:1,confirmed:1});f.op.effect='read';assert.equal((await f.router.invoke(f.op.id,{projectId:'p'},f.context)).ok,true);assert.equal(f.counts().confirmed,1);f.op.exposeTo=['page'];assert.equal((await f.router.invoke(f.op.id,{projectId:'p'},{caller:'agent',projectId:'p'})).error.code,'FORBIDDEN');assert.deepEqual(await f.router.list({caller:'agent',projectId:'p'}),[]);});
test('cross-project, cross-extension, malformed input never dispatch',async()=>{const f=fixture();for(const [input,context] of [[{projectId:'other'},f.context],[{projectId:'p'},{caller:'agent',projectId:'other'}],[{projectId:'p'},{...f.context,extensionId:'other'}],[null,f.context]])assert.equal((await f.router.invoke(f.op.id,input,context)).ok,false);assert.equal(f.counts().dispatched,0);});
test('confirmation cancellation and generation changes have no effect',async()=>{for(const action of ['cancel','generation']){const f=fixture();f.router.confirm=async()=>{if(action==='generation')f.item.generation++;return {cancel:action==='cancel'};};const r=await f.router.invoke(f.op.id,{projectId:'p'},f.context);assert.equal(r.ok,false);assert.equal(r.error.effectStatus,'notStarted');assert.equal(f.counts().dispatched,0);}});
test('ordinary exemptions scoped to caller, revision/generation; important risks always confirm',async()=>{const f=fixture({risk:{reversible:true,impacts:[]}});await f.router.invoke(f.op.id,{projectId:'p'},f.context);await f.router.invoke(f.op.id,{projectId:'p'},f.context);assert.equal(f.counts().confirmed,1);await f.router.invoke(f.op.id,{projectId:'p'},{caller:'agent',projectId:'p'});assert.equal(f.counts().confirmed,2);f.item.generation++;await f.router.invoke(f.op.id,{projectId:'p'},f.context);assert.equal(f.counts().confirmed,3);f.op.risk.impacts=['external'];await f.router.invoke(f.op.id,{projectId:'p'},f.context);await f.router.invoke(f.op.id,{projectId:'p'},f.context);assert.equal(f.counts().confirmed,5);});
test('revocation after dispatch suppresses output and reports unknown outcome',async()=>{const f=fixture();f.service.hosts.invoke=async(_i,_o,_p,opts)=>{await opts.guard();opts.onDispatch();f.item.generation++;return {secret:'must not escape'};};const r=await f.router.invoke(f.op.id,{projectId:'p'},f.context);assert.equal(r.ok,false);assert.equal(r.error.effectStatus,'unknown');assert.equal(r.value,undefined);});
test('invalidated approval aborts and cannot dispatch',async()=>{const f=fixture();f.router.confirm=async b=>{f.router.invalidate(f.item.id);assert.equal(b.abort.signal.aborted,true);return {};};assert.equal((await f.router.invoke(f.op.id,{projectId:'p'},f.context)).error.code,'CANCELLED');assert.equal(f.counts().dispatched,0);});
test('resource bridge enforces operation permission and bound project, filters metadata',async()=>{const f=fixture({effect:'read'});f.router.workspace={read:async()=>({projects:[{id:'p',name:'Project',path:'/private',description:'desc'}]})};const b={item:f.item,operation:f.op,input:{projectId:'p'},projectId:'p',context:f.context};assert.deepEqual(await f.router.resource(b,'getProject',{projectId:'p'}),{id:'p',name:'Project',description:'desc'});await assert.rejects(f.router.resource(b,'getProjectPath',{projectId:'p'}));await assert.rejects(f.router.resource(b,'getProject',{projectId:'other'}));});
