const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {validatePackage,validateManifest}=require('../core/extensions/manifest.cjs');const {Database}=require('../electron/database.cjs');const {ExtensionService}=require('../core/extensions/service.cjs');
const base={specVersion:'1.0-draft',publisher:'fixture',name:'icon',version:'1.0.0',displayName:'Icon test',engines:{api:'1'},skills:['skill']};
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'extension-icon-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));await fs.mkdir(path.join(root,'skill'));await fs.writeFile(path.join(root,'skill/SKILL.md'),'# Test');await fs.mkdir(path.join(root,'assets'));await fs.copyFile(path.resolve('public/brand/icon-128.png'),path.join(root,'assets/light.png'));await fs.copyFile(path.resolve('public/brand/icon-128.png'),path.join(root,'assets/dark.png'));return {root,write:m=>fs.writeFile(path.join(root,'extension.json'),JSON.stringify(m))};}
test('icons validate local paths, format, size, dimensions, completeness and themes',async t=>{const {root,write}=await fixture(t);for(const icon of ['assets/light.png',{light:'assets/light.png',dark:'assets/dark.png'}]){await write({...base,icon});const r=validatePackage(root);assert.equal(r.ok,true,JSON.stringify(r.errors));assert.match(r.icons.light,/^data:image\/png;base64,/);assert.equal(r.icons.dark,r.icons.light);}
 for(const icon of ['https://example.com/a.png','../outside.png','/absolute.png','assets/a.svg',{light:'assets/light.png'},{light:'assets/light.png',dark:'assets/dark.png',extra:'x'}])assert.equal(validateManifest({...base,icon}).ok,false);
 await write({...base,icon:'assets/missing.png'});assert.equal(validatePackage(root).ok,false);
 await fs.symlink(path.resolve('public/brand/icon-128.png'),path.join(root,'assets/link.png'));await write({...base,icon:'assets/link.png'});assert.equal(validatePackage(root).ok,false);
 await write({...base,icon:'assets/bad.png'});for(const bytes of [Buffer.from('<svg/>'),Buffer.alloc(65537),Buffer.from((await fs.readFile(path.resolve('public/brand/icon-128.png'))).subarray(0,33))]){await fs.writeFile(path.join(root,'assets/bad.png'),bytes);assert.equal(validatePackage(root).ok,false);}
 const huge=await fs.readFile(path.resolve('public/brand/icon-128.png'));huge.writeUInt32BE(4096,16);await fs.writeFile(path.join(root,'assets/bad.png'),huge);assert.equal(validatePackage(root).ok,false);
});
test('installed icon is available before activation, persists, and clears on update without icon',async t=>{const {root,write}=await fixture(t);await write({...base,icon:'assets/light.png'});const state=await fs.mkdtemp(path.join(os.tmpdir(),'extension-icon-db-')),db=new Database(state);await db.call('ready');const service=new ExtensionService(db,{directory:state});t.after(async()=>{await service.shutdown();await db.close();await fs.rm(state,{recursive:true,force:true});});await service.initialize();await service.installPackage(root,'directory',async()=>true);assert.match(service.snapshot().installed[0].manifest.icon.light,/^data:image\/png/);const reloaded=new ExtensionService(db,{directory:state});await reloaded.initialize();assert.deepEqual(reloaded.snapshot().installed[0].manifest.icon,service.snapshot().installed[0].manifest.icon);await write({...base,version:'1.0.1'});await service.installPackage(root,'directory',async()=>true);assert.equal(service.snapshot().installed[0].manifest.icon,undefined);});
