const test=require('node:test'),assert=require('node:assert/strict');const {createAgentChannel}=require('../core/extensions/agent-channel.cjs');const {OperationRouter}=require('../core/extensions/operations.cjs');
test('authenticated MCP binds each project, routes writes through approval and expires on close',async()=>{let dispatched=0,approved=0;const item={id:'t.e',kind:'package',enabled:true,trusted:true,active:'v1',generation:1,manifest:{operations:[{id:'t.e.write',title:'Write',description:'Write',effect:'write',projectScoped:true,exposeTo:['agent'],requiredPermissions:[],inputSchema:{}}]}};const service={items:[item],localized:(_i,s)=>s,displayName:()=> 'Test',packages:{validateValue:async()=>true},hosts:{entries:new Map(),invoke:async(_i,_o,_v,o)=>{await o.guard();o.onDispatch();dispatched++;return {};}}};const router=new OperationRouter({service,workspace:{read:async()=>({projects:[{id:'p'},{id:'q'}]})},confirm:async()=>{approved++;return {cancel:true};}});
 const channels=[];try{for(const projectId of ['p','q'])channels.push(await createAgentChannel({list:s=>router.list({caller:'agent',projectId,signal:s}),invoke:(id,input,s)=>router.invoke(id,input,{caller:'agent',projectId,signal:s})}));
 const call=(channel,token,input)=>fetch(channel.config.url,{method:'POST',headers:{Authorization:token,'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'extension_invoke_operation',arguments:{operationId:'t.e.write',input}}})});
 assert.equal((await call(channels[0],channels[1].config.http_headers.Authorization,{projectId:'p'})).status,403);
 let r=await (await call(channels[0],channels[0].config.http_headers.Authorization,{projectId:'q'})).json();assert.equal(JSON.parse(r.result.content[0].text).error.code,'FORBIDDEN');assert.equal(approved,0);
 r=await (await call(channels[0],channels[0].config.http_headers.Authorization,{projectId:'p'})).json();assert.equal(JSON.parse(r.result.content[0].text).error.code,'CANCELLED');assert.equal(approved,1);assert.equal(dispatched,0);
 channels[0].close();await assert.rejects(call(channels[0],channels[0].config.http_headers.Authorization,{projectId:'p'}));
 }finally{for(const c of channels)c.close();}});
test('closing an execution aborts pending MCP work and never replays it',async()=>{let calls=0,aborted=false,started;const ready=new Promise(r=>started=r);const channel=await createAgentChannel({list:async()=>[],invoke:async(_id,_input,signal)=>{calls++;started();await new Promise(resolve=>signal.addEventListener('abort',()=>{aborted=true;resolve();},{once:true}));return {ok:false,error:{code:'CANCELLED'}};}});const request=fetch(channel.config.url,{method:'POST',headers:{Authorization:channel.config.http_headers.Authorization},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'extension_invoke_operation',arguments:{operationId:'t.e.write',input:{}}}})});const rejected=assert.rejects(request);await ready;channel.close();await rejected;assert.equal(aborted,true);assert.equal(calls,1);});
test('engine MCP config contains no credential and applies only internal tool policy',()=>{const {configurationArgs}=require('../electron/codex-rpc.cjs');const args=configurationArgs({model:'fixture'},'/tmp/fixture',{url:'http://127.0.0.1:1/mcp',http_headers:{Authorization:'Bearer private-test-token'},tool_timeout_sec:270});assert.equal(JSON.stringify(args).includes('private-test-token'),false);assert.ok(args.includes('features.shell_snapshot=false'));assert.ok(args.includes('mcp_servers.amble_extensions.tools.extension_invoke_operation.approval_mode="approve"'));for(const tool of ['forms_list','forms_present'])assert.ok(args.includes('mcp_servers.amble_extensions.tools.'+tool+'.approval_mode="approve"'));assert.equal(args.some(a=>a.startsWith('mcp_servers.amble_extensions.approval_mode=')),false);assert.ok(args.includes('mcp_servers.amble_extensions.env_http_headers.Authorization="AMBLE_EXTENSION_AUTH"'));});
test('MCP Apps exposes standard resource metadata and structured results while keeping legacy tools',async()=>{
 const descriptor={name:'test.app.render',description:'Render',inputSchema:{type:'object'},_meta:{ui:{resourceUri:'ui://test.app/form',visibility:['model']}}};
 const channel=await createAgentChannel({list:async()=>[],tools:async()=>[descriptor],resource:async uri=>({contents:[{uri,mimeType:'text/html;profile=mcp-app',text:'<h1>Form</h1>'}]}),invoke:async()=>({ok:true,value:{amount:12}})});
 try{let id=0;const call=async(method,params={})=>(await (await fetch(channel.config.url,{method:'POST',headers:{...channel.config.http_headers,'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:++id,method,params})})).json()).result;
  assert.ok((await call('initialize')).capabilities.resources);
  const list=await call('tools/list');assert.equal(list.tools.length,3);assert.deepEqual(list.tools[2],descriptor);
  assert.deepEqual((await call('tools/call',{name:descriptor.name,arguments:{}})).structuredContent,{amount:12});
  assert.equal((await call('resources/list')).resources[0].uri,descriptor._meta.ui.resourceUri);
  assert.equal((await call('resources/read',{uri:descriptor._meta.ui.resourceUri})).contents[0].mimeType,'text/html;profile=mcp-app');
 }finally{channel.close();}
});
