const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const T=require('../core/forms/template.cjs');const {FormService}=require('../core/forms/service.cjs');const {Database}=require('../electron/database.cjs');
const source=()=>fs.readFile('specs/extensions/examples/declarative-forms/single-step.yaml','utf8');
test('strict YAML rejects unsafe and ambiguous definitions; AST ignores quoted examples',async()=>{const yaml=await source();const form=T.normalize(yaml);assert.equal(form.steps.length,1);for(const bad of [yaml+'\nunknown: true',yaml+'\ntitle: duplicate',yaml.replace('version: 1','version: &v 1'),yaml.replace('version: 1','version: !!int 1')])assert.throws(()=>T.normalize(bad));const found=await T.discover('> ```amble-form\n> '+yaml.split('\n').join('\n> ')+'\n> ```','/tmp');assert.equal(found.forms.length,0);assert.equal((await T.discover('```amble-form\n'+yaml+'\n```','/tmp')).forms.length,1);});
test('money/date/select validation is deterministic',async()=>{const step=T.normalize(await source()).steps[0];assert.equal(T.decimal('001.2').value,'1.20');assert.throws(()=>T.decimal('1e3'));assert.throws(()=>T.decimal('1.001'));const result=T.validateValues(step,{region:'wrong',amount:'0.001','travel-date':'2026-02-30'},{raw:true});assert.ok(result.errors.region);assert.ok(result.errors.amount);assert.ok(result.errors['travel-date']);});
test('conversation form persists, rejects stale saves, confirms once and never resubmits',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'forms-'));const database=new Database(dir);try{await fs.writeFile(path.join(dir,'SKILL.md'),'```amble-form\n'+await source()+'\n```');let starts=0;const run={id:'run',projectId:'p',messages:[]};const service=new FormService({database,skills:{list:async()=>[{id:'expense',path:path.join(dir,'SKILL.md'),revision:1,enabled:true}]},extensions:{items:[]},runtime:{runs:[run],start:async(input,context)=>{starts++;run.messages.push({formSubmissionId:context.formSubmissionId});assert.match(input.prompt,/上海/);}},publish:()=>{},confirm:async()=>true});const c=await service.catalog();assert.equal(c.errors.length,0);await service.present(run,'turn',c.entries[0].key);let [flow]=await service.list('run');flow=await service.action({runId:'run',id:flow.id,revision:flow.revision,action:'save',values:{region:'shanghai',amount:'12.30','travel-date':'2026-10-01'}},{});await assert.rejects(service.action({runId:'run',id:flow.id,revision:0,action:'next'},{}));const result=await service.action({runId:'run',id:flow.id,revision:flow.revision,action:'next'},{});assert.equal(result.status,'completed');await assert.rejects(service.action({runId:'run',id:flow.id,revision:result.revision,action:'next'},{}));assert.equal(starts,1);assert.equal((await service.list('run'))[0].status,'completed');}finally{await database.close();await fs.rm(dir,{recursive:true,force:true});}});
test('multi-step operation keeps submission identity and recovers unknown without replay',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'forms-flow-'));const database=new Database(dir);try{let calls=0;const template=T.normalize({version:1,id:'flow',title:'测试',steps:[{id:'first',title:'第一步',fields:[{name:'name',label:'姓名',type:'text',required:true}],next:{kind:'operation',label:'保存',operation:'example.demo.save',input:{name:{from:'steps.first.name'}},recovery:{operation:'example.demo.lookup'}}},{id:'last',title:'确认',fields:[{name:'confirm',label:'确认',type:'checkbox',required:true}]}],submit:{kind:'chat',label:'发送'}});const run={id:'r',messages:[]};let metadata;const service=new FormService({database,runtime:{runs:[run]},publish:()=>{},extensions:{packages:{validateValue:async()=>true}},router:{item:()=>({id:'ext',manifest:{operations:[{id:'example.demo.lookup',effect:'read'},{id:'example.demo.save',outputSchema:{}}]}}),invoke:async(id,input,ctx)=>{calls++;if(id.endsWith('save')){metadata=ctx.form;return {ok:false,error:{code:'TIMEOUT',effectStatus:'unknown'}};}assert.equal(input.submissionId,metadata.submissionId);return {ok:true,value:{status:'succeeded',result:{draftId:'draft'}}};}}});service.catalog=async()=>({entries:[{key:'ext:flow',extensionId:'ext',template,digest:T.hash(template),revision:1}],errors:[]});await service.present(run,'t','ext:flow');let [f]=await service.list('r');const act=(action,extra={})=>service.action({runId:'r',id:f.id,revision:f.revision,action,...extra},{});f=await act('save',{values:{name:'用户'}});f=await act('next');assert.equal(f.status,'unknown');assert.match(f.error,/TIMEOUT/);await assert.rejects(act('next'));assert.equal(calls,1);f=await act('reconcile');assert.equal(f.step,1);assert.equal(f.error,undefined);assert.equal((await service.list('r'))[0].error,undefined);assert.equal(f.results.first.draftId,'draft');assert.equal(metadata.flowInstanceId,f.id);f=await act('previous');f=await act('save',{values:{name:'新姓名'}});assert.equal(f.results.first,undefined);assert.equal(f.values.first,undefined);}finally{await database.close();await fs.rm(dir,{recursive:true,force:true});}});

test('final reconciliation clears persisted errors only for a confirmed outcome and never repeats the write',async()=>{
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'forms-reconcile-')),database=new Database(dir);
 try{
  for(const outcome of ['succeeded','notExecuted','unknown']){
   const run={id:'run-'+outcome,messages:[]},template=T.normalize({version:1,id:'claim',title:'Claim',fields:[{name:'amount',label:'Amount',type:'text',required:true}],submit:{kind:'operation',label:'Submit',operation:'example.claim.submit',input:{amount:{from:'steps.main.amount'}},recovery:{operation:'example.claim.lookup'}}});
   let writes=0,reads=0;
   const operations=[{id:'example.claim.submit',effect:'write',outputSchema:{}},{id:'example.claim.lookup',effect:'read'}];
   const service=new FormService({database,runtime:{runs:[run]},publish:()=>{},extensions:{packages:{validateValue:async()=>true}},router:{
    item:()=>({id:'example.claim',manifest:{operations}}),
    invoke:async id=>id.endsWith('submit')?(writes++,{ok:false,error:{code:'INTERNAL',effectStatus:'unknown'}}):(reads++,{ok:true,value:outcome==='succeeded'?{status:outcome,result:{claimId:'CL-001'}}:{status:outcome}})
   }});
   service.catalog=async()=>({entries:[{key:'claim',extensionId:'example.claim',template,digest:T.hash(template),revision:1}],errors:[]});
   await service.present(run,'turn','claim');
   let [flow]=await service.list(run.id);
   const act=(action,extra={})=>service.action({runId:run.id,id:flow.id,revision:flow.revision,action,...extra},{});
   flow=await act('save',{values:{amount:'1280'}});flow=await act('next');
   assert.match(flow.error,/INTERNAL/);const submissionId=flow.submission.id;
   flow=await act('reconcile');
   const [stored]=await service.list(run.id);
   assert.equal(stored.submission.id,submissionId);assert.equal(writes,1);assert.equal(reads,1);
   if(outcome==='unknown'){assert.equal(stored.status,'unknown');assert.match(stored.error,/INTERNAL/);}
   else{assert.equal(stored.error,undefined);assert.equal(stored.status,outcome==='succeeded'?'completed':'editing');}
   if(outcome==='succeeded'){
    assert.equal(stored.results.main.claimId,'CL-001');
    stored.error='提交未完成：INTERNAL';await service.write(stored,stored.revision);
    const [repaired]=await service.list(run.id);assert.equal(repaired.error,undefined);
    assert.equal(repaired.results.main.claimId,'CL-001');assert.equal(writes,1);
   }
  }
 }finally{await database.close();await fs.rm(dir,{recursive:true,force:true});}
});
