const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const T=require('../packages/extension-core/lib/forms.cjs');const host=require('../../agent/core/forms/template.cjs');
const yaml=`version: 1\nid: demo\ntitle: Demo\nfields:\n - {name: amount, type: money, currency: CNY, label: Amount, required: true}\nsubmit: {kind: chat, label: Send}\n`;
test('host differential parser fixtures: strict YAML and schema',()=>{
 const fixtures=[yaml,yaml+'unknown: true',yaml+'id: duplicate',yaml.replace('Demo','&anchor Demo'),yaml.replace('Demo','!!str Demo'),yaml.replace('Demo','.inf'),yaml.replace('currency: CNY,',''),yaml.replace('type: money','type: password'),yaml.replace('required: true','required: true, options: []'),'x'.repeat(128*1024+1),yaml.replace('id: demo','__proto__: x\nid: demo'),yaml.replace('id: demo','id: *bad')];
 for(const source of fixtures){let a,b;try{a={value:T.normalize(source)}}catch(e){a={error:e.message}}try{b={value:host.normalize(source)}}catch(e){b={error:e.message}}assert.deepEqual(a,b);}
});
test('host differential field values and precision',()=>{const fields=[{name:'n',type:'number',integer:true},{name:'m',type:'money',scale:2,currency:'CNY'},{name:'d',type:'date'},{name:'s',type:'select',options:[{label:'上海',value:'shanghai'}]},{name:'c',type:'checkbox',required:true}];for(const v of [{n:1,m:'12.30',d:'2026-10-01',s:'shanghai',c:true},{n:2**53,m:'1.234',d:'2026-02-30',s:'上海',c:false}])assert.deepEqual(T.validateValues({fields},v),host.validateValues({fields},v));assert.equal(T.validateValues({fields}, {n:2**53,m:'1.234',d:'2026-02-30',s:'上海',c:false}).errors.c,'请勾选后继续');});
test('AST root only, safe reference paths, symlinks, duplicate ids across skills',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'forms-'));try{await fs.mkdir(path.join(root,'s'));await fs.writeFile(path.join(root,'s/f.yaml'),yaml);const body='```amble-form-ref\npath: f.yaml\n```\n\n> ```amble-form\n> bad\n> ```';assert.equal((await T.discover(body,path.join(root,'s'))).forms.length,1);for(const ref of ['../escape','/tmp/escape','link']){if(ref==='link')await fs.symlink('f.yaml',path.join(root,'s/link'));assert.equal((await T.discover('```amble-form-ref\npath: '+ref+'\n```',path.join(root,'s'))).errors.length,1);}await fs.writeFile(path.join(root,'s/SKILL.md'),body);const result=await T.validateForms(root,{skills:['s','s']});assert.equal(result.errors[0].code,'FORM_DUPLICATE');}finally{await fs.rm(root,{recursive:true,force:true});}});
test('expense binding checks reject missing mapping, result, recovery and project drift',async()=>{const root=path.resolve(__dirname,'../examples/expense');const m=JSON.parse(await fs.readFile(path.join(root,'extension.json')));assert.deepEqual((await T.validateForms(root,m)).errors,[]);const bad=structuredClone(m);bad.operations[0].projectScoped=true;bad.operations[0].exposeTo=['agent'];assert.ok((await T.validateForms(root,bad)).errors.some(e=>e.code==='FORM_OPERATION'));const bad2=structuredClone(m);bad2.operations[0].inputSchema.required.push('missing');bad2.operations[1].outputSchema.properties.result={type:'object',properties:{different:{type:'string'}},required:['different'],additionalProperties:false};const result=await T.validateForms(root,bad2);assert.ok(result.errors.some(e=>e.code==='FORM_REQUIRED'));assert.ok(result.errors.some(e=>e.code==='FORM_RECOVERY_RESULT'));});
test('backend refuses forged input.form before configuration or network access',async()=>{const handlers={};const code=require('esbuild').buildSync({entryPoints:[path.resolve(__dirname,'../examples/expense/src/main.ts')],bundle:true,platform:'node',format:'cjs',write:false}).outputFiles[0].text;const module=new (require('node:module'))(path.join(__dirname,'backend-fixture.cjs'));module._compile(code,module.id);const {activate}=module.exports;activate({subscriptions:[],operations:{register(name,fn){handlers[name]=fn;return{dispose(){}};}},configuration:{get(){throw Error('must not read configuration');}}});await assert.rejects(handlers.saveDraft({region:'shanghai',date:'2026-10-01',form:{submissionId:'forged'}},{signal:new AbortController().signal,requestId:'not-a-submission',caller:'page'}),e=>e.code==='UNSUPPORTED');});
test('CLI form limit and invalid result reference fixtures match host boundaries',()=>{const base={version:1,id:'test',title:'Test',fields:[{name:'x',type:'text',label:'X'}],submit:{kind:'chat',label:'Send'}};const variants=[{...base,steps:[{id:'a',title:'A',fields:base.fields}]},{...base,fields:Array.from({length:101},(_,i)=>({name:'x'+i,type:'text',label:'X'}))},{...base,fields:[{name:'x',type:'select',label:'X',options:[{label:'A',value:'a'},{label:'B',value:'a'}]}]},{...base,fields:[{name:'x',type:'number',label:'X',minimum:2,maximum:1}]}];for(const fixture of variants){assert.throws(()=>T.normalize(fixture));assert.throws(()=>host.normalize(fixture));}});
test('project fixture validates and CLI rejects cross-source/result/type/missing recovery',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'forms-binding-'));try{await fs.mkdir(path.join(dir,'skills/expense/forms'),{recursive:true});const manifest=JSON.parse(await fs.readFile(path.join(__dirname,'fixtures/forms/project-scoped.extension.json')));const source=await fs.readFile(path.join(__dirname,'fixtures/forms/project-scoped.yaml'),'utf8');await fs.writeFile(path.join(dir,'skills/expense/SKILL.md'),'```amble-form-ref\npath: forms/travel.yaml\n```');const file=path.join(dir,'skills/expense/forms/travel.yaml');await fs.writeFile(file,source);assert.deepEqual((await T.validateForms(dir,manifest)).errors,[]);
 for(const [needle,replacement,code]of [['operation: example.expense.saveDraft','operation: other.expense.saveDraft','FORM_OPERATION'],['results.itinerary.draftId','results.itinerary.missing','FORM_RESULT_FIELD'],['steps.expenses.amount','steps.confirmation.confirmed','FORM_TYPE'],['        projectId: {from: context.projectId}\n','','FORM_PROJECT'],['      recovery: {operation: example.expense.lookupDraft}\n','','FORM_RECOVERY_REQUIRED']]){await fs.writeFile(file,source.replace(needle,replacement));assert.ok((await T.validateForms(dir,manifest)).errors.some(e=>e.code===code),code);}
 }finally{await fs.rm(dir,{recursive:true,force:true});}});
test('expense and MCP Apps templates retain identical source and exclude service from extension build',async()=>{for(const name of ['expense','task-form']){const base=path.resolve(__dirname,'../examples',name),template=path.resolve(__dirname,'../packages/cli/templates',name);async function compare(dir=''){for(const item of await fs.readdir(path.join(base,dir),{withFileTypes:true})){if(['dist','node_modules'].includes(item.name))continue;const file=path.join(dir,item.name);if(item.isDirectory())await compare(file);else assert.deepEqual(await fs.readFile(path.join(base,file)),await fs.readFile(path.join(template,file)),name+'/'+file);}}await compare();}});
