import { _electron as electron } from '@playwright/test';
import { mkdtemp, writeFile, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const directory=await mkdtemp(path.join(tmpdir(),'atelier-chat-'));
const run={id:'visual',title:'为设计师打造本地 AI 工作台',model:'DeepSeek-v4-flash',baseUrl:'http://127.0.0.1/v1',cwd:'/demo/design',createdAt:new Date().toISOString(),status:'completed',error:'',approvals:[],tools:[],messages:[{id:'u',role:'user',text:'请设计一个简单的本地 Agent 工作流，给我一份清晰的方案。'},{id:'r',role:'assistant',kind:'reasoning',status:'completed',text:'先明确输入与交付物，再将模型推理、工具执行和用户确认分开展示。'},{id:'a',role:'assistant',text:'# 让创作保持流畅\n\n将过程分为 **理解需求 → 生成方案 → 确认执行**，每一步都可查看和停止。\n\n| 环节 | 界面反馈 |\n|---|---|\n| 思考 | 可展开摘要 |\n| 执行 | 工具状态与结果 |\n| 授权 | 输入框上方确认 |\n\n```mermaid\nflowchart LR\n A[你的想法] --> B[本地模型]\n B --> C[方案预览]\n C --> D[确认执行]\n```\n\n```echarts\n{"xAxis":{"type":"category","data":["理解","生成","执行"]},"yAxis":{},"series":[{"type":"bar","data":[3,7,4],"itemStyle":{"color":"#6182bc"}}]}\n```\n\n```drawio\n<mxGraphModel><root><mxCell id="0"/><mxCell id="1" parent="0"/><mxCell id="a" value="想法" vertex="1" parent="1" style="rounded=1;"><mxGeometry x="20" y="20" width="120" height="60" as="geometry"/></mxCell><mxCell id="b" value="作品" vertex="1" parent="1"><mxGeometry x="240" y="20" width="120" height="60" as="geometry"/></mxCell><mxCell id="e" edge="1" source="a" target="b" parent="1"><mxGeometry relative="1" as="geometry"/></mxCell></root></mxGraphModel>\n```\n'}]};
run.messages[0].timing={startedAt:new Date().toISOString(),durationMs:65000,outcome:'completed'};
await writeFile(path.join(directory,'conversations.json'),JSON.stringify([run]));
let app;
try {
 app=await electron.launch({args:['.',`--user-data-dir=${directory}`],env:{...process.env,ATELIER_DEV:'0'}});
 const page=await app.firstWindow(); await page.locator('.tree-task > button:first-child').filter({hasText:'为设计师打造本地 AI 工作台'}).click();
 assert.equal(await page.locator('.process-panel').count(),0);
 await page.getByAltText('Mermaid 图表').waitFor();
 await page.locator('.chart-canvas svg').waitFor();
 await page.getByRole('img',{name:'draw.io 基础图形'}).waitFor();
 assert.equal(await page.getByAltText('Mermaid 图表').evaluate(img=>img.naturalWidth>0),true);
 await mkdir('test-results',{recursive:true});
 await page.locator('.conversation-scroll').evaluate(el=>el.scrollTop=0);
 await page.screenshot({path:'test-results/chat-rich.png'});
 const pending={...run,status:'waiting',approvals:[{id:'request-1',method:'item/commandExecution/requestApproval',detail:JSON.stringify({command:'mkdir -p design-output',cwd:'/demo/design',reason:'为方案产物创建文件夹，需要写入权限。'},null,2)}]};
 await app.evaluate(({BrowserWindow},value)=>BrowserWindow.getAllWindows()[0].webContents.send('agent:event',value),pending);
 await page.getByRole('button',{name:'批准本次',exact:true}).waitFor();
 await page.screenshot({path:'test-results/chat-approval.png'});
 await page.locator('.conversation-scroll').evaluate(el=>el.scrollTop=el.scrollHeight);
 await page.screenshot({path:'test-results/chat-diagrams.png'});
 const progress={...run,status:'running',approvals:[],messages:[...run.messages,{id:'u2',role:'user',text:'把方案整理成 Word 文档。'},{id:'p1',role:'assistant',phase:'commentary',text:'有个 Python 3.11 可用。现在用 uv 在虚拟环境里安装 python-docx。',order:1},{id:'p2',role:'assistant',phase:'commentary',text:'安装进行中，等待完成。',order:3}],tools:[{id:'t',turnKey:'u2',type:'commandExecution',label:'uv pip install python-docx',status:'inProgress',detail:'Downloading python-docx…',order:2}]};
 await app.evaluate(({BrowserWindow},value)=>BrowserWindow.getAllWindows()[0].webContents.send('agent:event',value),progress);
 await page.locator('.process-panel').waitFor();
 await page.locator('.turn-anchor').nth(1).click();
 await page.screenshot({path:'test-results/chat-process-desktop.png'});
 await page.locator('.turn-anchor').first().hover();
 await page.getByRole('tooltip').waitFor();
 await page.screenshot({path:'test-results/chat-anchor-desktop.png'});
 const finished={...progress,status:'completed',messages:[...progress.messages,{id:'f2',role:'assistant',phase:'final_answer',text:'文档已生成，包含完整方案与工作流。'}]};
 await app.evaluate(({BrowserWindow},value)=>BrowserWindow.getAllWindows()[0].webContents.send('agent:event',value),finished);
 await page.locator('.process-panel').waitFor({state:'detached'});
 assert.equal(await page.locator('.message.assistant').count(),2);
 console.log('Desktop passed: rich rendering, approval dock, turn anchors and progress-to-final transition.');
}finally {await app?.close();await rm(directory,{recursive:true,force:true});}
