const {randomUUID}=require('node:crypto');const path=require('node:path');
const packaged=process.resourcesPath&&path.join(process.resourcesPath,'tools/form-template.cjs');
const T=require(packaged&&require('node:fs').existsSync(packaged)?packaged:'./template.cjs');
class FormService{
 constructor(options){Object.assign(this,options);this.queue=Promise.resolve();}
 serial(fn){const p=this.queue.then(fn);this.queue=p.catch(()=>{});return p;}
 async catalog(){const entries=[],errors=[];const sources=(await this.skills.list()).filter(s=>s.enabled!==false).map(s=>({key:'skill:'+s.id,root:path.dirname(s.path),revision:s.revision}));
  for(const item of this.extensions.items.filter(i=>i.kind==='package'&&i.enabled&&i.trusted&&!i.pending)){const revision=item.revisions.find(r=>r.digest===item.active);if(!revision)continue;const checked=await this.extensions.packages.prepare(path.join(this.extensions.packages.root,revision.relativePath),'directory');if(checked.digest!==item.active)continue;for(const skill of item.manifest.skills||[])sources.push({key:'extension:'+item.id,extensionId:item.id,root:path.join(this.extensions.packages.root,revision.relativePath,skill),revision:item.active});}
  for(const source of sources)try{const body=await T.safeRead(source.root,'SKILL.md');const found=await T.discover(body,source.root);errors.push(...found.errors.map(e=>({...e,source:source.key})));for(const template of found.forms){const key=source.key+':'+template.id;if(source.extensionId)for(const action of [template.submit,...template.steps.map(s=>s.next)].filter(a=>a?.kind==='operation')){const item=this.extensions.items.find(i=>i.id===source.extensionId);const op=item.manifest.operations?.find(o=>o.id===action.operation);if(!op||!op.exposeTo.includes('page'))throw Error('操作必须由当前扩展注册并允许页面调用');if(op.effect==='write'&&!action.recovery)throw Error('写操作必须提供核实接口');if(action.recovery){const recovery=item.manifest.operations.find(o=>o.id===action.recovery.operation);if(!recovery||recovery.effect!=='read'||!recovery.exposeTo.includes('page'))throw Error('无效的只读核实接口');}}if(entries.some(e=>e.key===key))throw Error('表单标识重复');if(!source.extensionId&&[template.submit,...template.steps.map(s=>s.next)].some(a=>a?.kind==='operation'))throw Error('个人 Skill 暂不支持业务操作，请通过扩展注册');entries.push({...source,key,template,digest:T.hash(template)});}}catch(e){errors.push({source:source.key,message:e.message});}return {entries,errors};
 }
 async rows(runId){return this.database.call('formData',{action:'list',runId});}
 async write(flow,revision){if(flow.submission){flow.submissions ||= [];const index=flow.submissions.findIndex(s=>s.id===flow.submission.id);const record=structuredClone(flow.submission);if(index<0)flow.submissions.push(record);else flow.submissions[index]=record;}const value=await this.database.call('formData',{action:'put',flow,revision});this.publish();return value;}
 async list(runId){return this.serial(async()=>{const rows=await this.rows(runId);for(let flow of rows)if(flow.status==='unknown'&&this.runtime.runs.find(r=>r.id===runId)?.messages.some(m=>m.formSubmissionId===flow.submission?.id)){flow.status='completed';flow.submission.status='succeeded';await this.write(flow,flow.revision);}return this.rows(runId);});}
 async present(run,turnKey,key,prefill={}){return this.serial(async()=>{const c=await this.catalog(),entry=c.entries.find(e=>e.key===key);if(!entry)throw Error('表单不可用');const existing=(await this.rows(run.id)).find(f=>f.turnKey===turnKey&&f.key===key);if(existing)return {id:existing.id,status:existing.status};const drafts={};for(const [stepId,values]of Object.entries(prefill)){const step=entry.template.steps.find(s=>s.id===stepId);if(!step)throw Error('未知步骤');const checked=T.validateValues(step,values,{partial:true});if(Object.keys(checked.errors).length)throw Error('预填数据无效');drafts[stepId]=checked.values;}
 const flow={id:randomUUID(),runId:run.id,conversationId:run.conversationId||run.id,turnKey,key,extensionId:entry.extensionId,digest:entry.digest,sourceRevision:entry.revision,template:entry.template,projectId:run.projectId,drafts,values:{},results:{},step:0,status:'editing',revision:0};await this.write(flow,null);return {id:flow.id,status:flow.status};});}
 async action(input,owner){return this.serial(async()=>{let flow=(await this.rows(input.runId)).find(f=>f.id===input.id);if(!flow||flow.revision!==input.revision)throw Error('表单已在其他窗口更新，请重新载入。当前输入仍保留。');const run=this.runtime.runs.find(r=>r.id===flow.runId);if(!run||run.archivedAt)throw Error('请先还原聊天');if(flow.status==='completed')throw Error('表单已完成');const entry=(await this.catalog()).entries.find(e=>e.key===flow.key);if(!entry||entry.digest!==flow.digest||entry.revision!==flow.sourceRevision)throw Error('表单来源已停用或更新，请重新打开一份表单');
 const validate=async()=>{const now=(await this.catalog()).entries.find(e=>e.key===flow.key);if(!now||now.digest!==flow.digest||now.revision!==flow.sourceRevision||run.archivedAt||run.projectId!==flow.projectId)throw Object.assign(Error('表单来源或聊天已变更'),{code:'FORBIDDEN'});};
 const step=flow.template.steps[flow.step];const persist=async()=>{flow=await this.write(flow,flow.revision);return flow;};
 if(input.action==='save'){if(flow.status!=='editing')throw Error('请先核实上次提交结果');if(JSON.stringify(input.values).length>128*1024)throw Error('表单内容过大');T.validateValues(step,input.values,{partial:true,raw:true});if(JSON.stringify(flow.drafts[step.id])!==JSON.stringify(input.values)){flow.drafts[step.id]=input.values;for(let i=flow.step;i<flow.template.steps.length;i++){const s=flow.template.steps[i];delete flow.values[s.id];delete flow.results[s.id];if(i>flow.step)for(const f of s.fields)if(f.type==='checkbox'&&f.required&&flow.drafts[s.id])flow.drafts[s.id][f.name]=false;}}return persist();}
 if(input.action==='previous'){if(flow.status!=='editing')throw Error('请先核实上次提交结果');flow.step=Math.max(0,flow.step-1);return persist();}
 if(input.action==='reconcile'&&flow.status==='unknown'){
 const action=flow.step===flow.template.steps.length-1?flow.template.submit:step.next;if(!action?.recovery)throw Error('此表单未提供核实接口，请联系业务服务');const recoveryId=typeof action.recovery==='string'?action.recovery:action.recovery.operation;const item=this.router.item(recoveryId),op=item.manifest.operations.find(o=>o.id===recoveryId);if(item.id!==flow.extensionId||op.effect!=='read')throw Error('核实接口必须是本扩展的只读操作');
 const result=await this.router.invoke(recoveryId,{submissionId:flow.submission.id,...(op.projectScoped?{projectId:flow.projectId}:{})},{caller:'page',extensionId:flow.extensionId,owner,validate});
 if(result.ok&&result.value?.status==='succeeded'){const original=this.router.item(action.operation).manifest.operations.find(o=>o.id===action.operation);if(!await this.extensions.packages.validateValue(original.outputSchema,result.value.result))throw Error('核实结果格式无效');flow.results[step.id]=result.value.result;flow.submission.status='succeeded';flow.status=flow.step===flow.template.steps.length-1?'completed':'editing';if(flow.status==='editing')flow.step++;}else if(result.ok&&result.value?.status==='notExecuted'){flow.status='editing';flow.submission.status='notExecuted';}return persist();
 }
 if(flow.status==='unknown')throw Error('上次提交结果待核实，请联系业务服务确认，不能重复提交');
 if(input.action!=='next')throw Error('不支持的表单操作');const checked=T.validateValues(step,flow.drafts[step.id]||{},{raw:true});if(Object.keys(checked.errors).length)return {flow,errors:checked.errors};flow.values[step.id]=checked.values;
 if(flow.template.steps.slice(0,flow.step).some(s=>!flow.values[s.id]))throw Error('请先完成前面的步骤');const final=flow.step===flow.template.steps.length-1,action=final?flow.template.submit:step.next;
 if(!action){flow.step++;return persist();}
 delete flow.error;const submissionId=randomUUID();flow.submission={id:submissionId,status:'prepared'};await persist();
 if(action.kind==='chat'){
  const text=[flow.template.title,...flow.template.steps.flatMap(s=>s.fields.map(f=>{let v=flow.values[s.id]?.[f.name];if(v===undefined)return '';if(f.type==='select')v=f.options.find(o=>o.value===v)?.label;if(f.type==='checkbox')v=v?'是':'否';return `${f.label}：${v}${f.type==='money'?' '+f.currency:''}`;}))].filter(Boolean).join('\n');
  if(!await this.confirm(owner,flow.template.title,text)){flow.submission.status='notExecuted';return persist();}
  await validate();flow.status='unknown';flow.submission.status='dispatched';await persist();
  try{await this.runtime.start({runId:run.id,prompt:text},{owner,formSubmissionId:submissionId});flow.status='completed';flow.submission.status='succeeded';}catch(e){if(this.runtime.runs.find(r=>r.id===run.id)?.messages.some(m=>m.formSubmissionId===submissionId)){flow.status='completed';flow.submission.status='succeeded';}else{flow.status='editing';flow.submission.status='notExecuted';flow.error=e.message;}}return persist();
 }
 const data={};for(const [key,b]of Object.entries(action.input)){if(Object.hasOwn(b,'value'))data[key]=b.value;else if(b.from==='context.projectId')data[key]=flow.projectId;else{const [kind,sid,field]=b.from.split('.');data[key]=(kind==='steps'?flow.values:flow.results)[sid]?.[field];}}
 flow.status='unknown';flow.submission.status='dispatched';await persist();
 const result=await this.router.invoke(action.operation,data,{caller:'page',extensionId:flow.extensionId,projectId:flow.projectId,owner,validate,form:{flowInstanceId:flow.id,stepId:step.id,submissionId,templateDigest:flow.digest,conversationId:flow.conversationId}});
 if(result.ok){flow.results[step.id]=result.value;flow.submission.status='succeeded';flow.status=final?'completed':'editing';if(!final)flow.step++;}else{flow.error='提交未完成：'+result.error.code;if(result.error.effectStatus==='notStarted'){flow.status='editing';flow.submission.status='notExecuted';}}
 return persist();
 });}
}
module.exports={FormService};
