import ManagementDialog from './ManagementDialog';
import {Button} from './components/ui/button';
import {Input} from './components/ui/input';
import {Field,FieldLabel,FieldDescription,FieldGroup} from './components/ui/field';
import {Badge} from './components/ui/badge';
import {Alert,AlertDescription} from './components/ui/alert';
import {SettingsCard,SettingsEmpty} from './SettingsPrimitives';
import {useEffect,useState,useRef} from 'react';
import {Plus,KeyRound} from 'lucide-react';
import {t} from './i18n';
import type {ConnectionCatalog,EnterpriseConnection} from './types';
export default function AccountSettings({onStateChange,onCancel}:{onStateChange?(dirty:boolean,busy:boolean):void;onCancel?(action:()=>void):void}){const [deleting,setDeleting]=useState<EnterpriseConnection|null>(null);const api=window.desktop?.authentication;const [catalog,setCatalog]=useState<ConnectionCatalog>({revision:0,defaultId:null,connections:[]}),[editor,setEditor]=useState<Partial<EnterpriseConnection>|null>(null),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{let alive=true;const load=()=>api?.connections().then(s=>{if(alive)setCatalog(s);}).catch(e=>{if(alive)setError(e.message);});void load();const dispose=api?.onChanged(()=>void load());return()=>{alive=false;dispose?.();};},[]);
 const [sessions,setSessions]=useState<{id:string;extensionName:string;account:{name:string};expiresAt:number}[]>([]);
 useEffect(()=>{let alive=true;const load=()=>api?.sessions?.().then(rows=>{if(alive)setSessions(rows);}).catch(()=>{});void load();const dispose=api?.onChanged(()=>void load());return()=>{alive=false;dispose?.();};},[api]);
 const [notice,setNotice]=useState('');
 const original=useRef('');
 const dirty=!!editor&&JSON.stringify(editor)!==original.current;
 useEffect(()=>{onStateChange?.(dirty,busy);},[dirty,busy,onStateChange]);
 const startEdit=(next:Partial<EnterpriseConnection>)=>{original.current=JSON.stringify(next);setNotice('');setEditor(next);};
 const mutate=async(input:Parameters<NonNullable<typeof api>['connections']>[0])=>{setBusy(true);setError('');try{setCatalog(await api!.connections(input));return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}};
 return <><div className="section-heading"><h1>{t('账号')}</h1><Button variant="default" disabled={!api||busy||!!editor} onClick={()=>{setRevision(catalog.revision);startEdit({name:'',issuer:'',clientId:'',tenant:''});setError('');}}><Plus size={16}/>{t('添加认证配置')}</Button></div><p className="page-description">{t('管理扩展使用的登录账号和认证配置。本地功能无需登录。')}</p>{notice&&<p role="status" className="text-sm text-muted-foreground">{notice}</p>}{error&&<Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}
 <SettingsCard title={t('已登录账号')}>{!sessions.length?<p>{t('暂无已登录账号。需要登录时，请在扩展中点击“连接账号”。')}</p>:sessions.map(session=><div className="setting-row" key={session.id}><span>{session.account.name}<small>{session.extensionName} · {t(session.expiresAt>Date.now()?'已连接':'请重新登录')}</small></span><Button variant="outline" disabled={busy} onClick={async()=>{setBusy(true);try{await api!.disconnect({id:session.id});setSessions(await api!.sessions());}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{t('断开连接')}</Button></div>)}</SettingsCard>
 {editor?<form className="flex max-w-2xl flex-col gap-4" onSubmit={async e=>{e.preventDefault();if(await mutate({action:'save',expectedRevision:revision,value:editor})){setEditor(null);setNotice(t('认证配置已保存，可在扩展登录时使用。'));}}}><h2>{t(editor.id?'编辑认证配置':'添加认证配置')}</h2><p className="text-sm text-muted-foreground">{t('支持 OpenID Connect（OIDC）身份认证服务。请填写服务提供方给出的配置。')}</p><FieldGroup>
 {(['name','issuer','clientId'] as const).map((key,i)=><Field key={key}><FieldLabel htmlFor={'auth-'+key}>{t(['配置名称','认证服务地址（Issuer URL）','客户端 ID（Client ID）'][i])}</FieldLabel><Input id={'auth-'+key} required type={key==='issuer'?'url':'text'} value={editor[key]||''} disabled={busy} maxLength={2048} aria-describedby={'auth-'+key+'-help'} placeholder={key==='issuer'?'https://login.example.com':undefined} onChange={e=>setEditor({...editor,[key]:e.target.value})}/><FieldDescription id={'auth-'+key+'-help'}>{t(['用于在登录时识别此配置，可自行命名。','填写以 https:// 开头的认证服务地址，不是登录页面的网址。','由认证服务提供方分配的应用标识，不是账号或密码。'][i])}</FieldDescription></Field>)}
 <details open={editor.tenant?true:undefined}><summary className="cursor-pointer text-sm">{t('高级选项（可选）')}</summary><Field className="mt-3"><FieldLabel htmlFor="auth-tenant">{t('租户限制')}</FieldLabel><Input id="auth-tenant" value={editor.tenant||''} disabled={busy} maxLength={256} aria-describedby="auth-tenant-help" onChange={e=>setEditor({...editor,tenant:e.target.value})}/><FieldDescription id="auth-tenant-help">{t('仅在服务提供方要求限制租户时填写，否则留空。')}</FieldDescription></Field></details>
 </FieldGroup><p>{t('保存配置不会自动登录。请在需要登录的扩展中选择此配置并完成登录。')}</p><div className="settings-actions"><Button variant="outline" type="button" disabled={busy} onClick={()=>onCancel?onCancel(()=>setEditor(null)):setEditor(null)}>{t('取消')}</Button><Button variant="default" type="submit" disabled={busy}>{t(busy?'正在保存…':'保存配置')}</Button></div></form>:<><h2 className="account-section-title">{t('自定义认证')}</h2><p className="text-sm text-muted-foreground mb-4">{t('配置扩展登录时使用的认证服务。仅在扩展要求时添加。')}</p>{!catalog.connections.length&&<SettingsEmpty icon={<KeyRound/>} title={t('尚未添加认证配置')} description={t('需要接入自己的身份认证服务时再添加。请向服务提供方获取服务地址和客户端 ID。')}/>}{catalog.connections.map(c=><SettingsCard key={c.id} title={c.name}><div className="section-heading">{catalog.defaultId===c.id&&<Badge variant="secondary">{t('默认配置')}</Badge>}</div><p className="connection-issuer">{c.issuer}</p><small>{t('客户端 ID')}：{c.clientId}</small><div className="settings-actions"><Button variant="outline" disabled={busy} onClick={()=>{setRevision(catalog.revision);startEdit(c);setError('');}}>{t('编辑')}</Button><Button variant="ghost" disabled={busy} onClick={()=>void mutate({action:'default',expectedRevision:catalog.revision,id:catalog.defaultId===c.id?null:c.id})}>{t(catalog.defaultId===c.id?'取消默认':'设为默认')}</Button><Button variant="destructive" disabled={busy} onClick={()=>{setDeleting(c);}}>{t('删除')}</Button></div></SettingsCard>)}</>}
 {deleting&&<ManagementDialog title={t('删除认证配置')} busy={busy} close={()=>setDeleting(null)}><p>{t('删除此认证配置后，将无法使用它发起新的登录。')}</p><strong>{deleting.name}</strong>{error&&<Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}<div className="flex justify-end gap-2"><Button variant="outline" disabled={busy} onClick={()=>setDeleting(null)}>{t('取消')}</Button><Button variant="destructive" disabled={busy} onClick={async()=>{if(await mutate({action:'remove',expectedRevision:catalog.revision,id:deleting.id}))setDeleting(null);}}>{t('删除')}</Button></div></ManagementDialog>}
 </>;
}
