import {useId,useState,type Dispatch,type SetStateAction} from 'react';
import {ArrowRight,BookOpen,ChevronRight,Cloud,Cpu,Folder,Laptop,PencilLine,Puzzle,Search,ShieldCheck} from 'lucide-react';
import {t} from './i18n';
import Modal from './Modal';
import SkillManager from './SkillManager';
import type {Capability,Model} from './types';
import type {CatalogDirectory,PluginListing} from './catalog-service';
export interface ModelView {query:string;filter:'all'|'local'|'cloud'}
export interface CapabilityView {tab:'skills'|'plugins';skills:{query:string;category:string};plugins:{query:string;category:string}}
export const initialModelView:ModelView={query:'',filter:'all'};
export const initialCapabilityView:CapabilityView={tab:'skills',skills:{query:'',category:'all'},plugins:{query:'',category:'all'}};
const icons={folder:Folder,pen:PencilLine,research:BookOpen};
const matches=(query:string,...values:string[])=>values.map(v=>`${v} ${t(v)}`).join(' ').toLocaleLowerCase().includes(query.trim().toLocaleLowerCase());
function DirectoryStatus({directory}:{directory:CatalogDirectory}){return directory.error?<div className="catalog-banner" role="alert"><span>{t(directory.error)}</span><button className="text-button" onClick={directory.reload}>{t('重试')}</button></div>:directory.loading?<p role="status" className="fine-print">{t('正在加载目录…')}</p>:null;}
export function ModelCatalogPage({directory,view,setView,choose}:{directory:CatalogDirectory;view:ModelView;setView:Dispatch<SetStateAction<ModelView>>;choose(model:Model):void}){
 const [detail,setDetail]=useState<Model|null>(null);
 const visible=directory.data.models.filter(model=>matches(view.query,model.name,model.description,...model.tags)&&(view.filter==='all'||model.location===view.filter));
 return <div className="content-page catalog-page"><div className="page-heading"><div><div className="eyebrow">MODEL LIBRARY</div><h1>{t('找到与你合拍的模型')}</h1><p className="page-description">{t('留在本地，或连接云端。选择权始终在你手中。')}</p></div><div className="heading-illustration"><Cpu size={44} strokeWidth={1}/></div></div><div className="catalog-banner"><ShieldCheck size={19}/><div><strong>{t('精选目录 · 规划预览')}</strong><p>{t('以下是模型接入方向。具体版本、设备要求与下载将在验证后开放。')}</p></div></div><DirectoryStatus directory={directory}/><div className="catalog-controls"><div className="segments" aria-label={t('模型筛选')}>{([{id:'all',label:'全部'},{id:'local',label:'本地模型'},{id:'cloud',label:'云端服务'}] as const).map(filter=><button key={filter.id} aria-pressed={view.filter===filter.id} className={view.filter===filter.id?'selected':''} onClick={()=>setView({...view,filter:filter.id})}>{t(filter.label)}</button>)}</div><label className="search-field"><Search size={16}/><input type="search" aria-label={t('搜索模型')} placeholder={t('搜索模型或用途')} value={view.query} onChange={e=>setView({...view,query:e.target.value})}/></label></div><div className="model-grid">{visible.map(model=><button className="model-card surface-card" key={model.id} onClick={()=>setDetail(model)}><div className="model-card-top"><span className={`model-avatar ${model.color}`}>{model.initials}</span><span className="badge neutral">{model.location==='local'?<Laptop size={11}/>:<Cloud size={11}/>} {t(model.location==='local'?'本地候选':'云端规划')}</span></div><h2>{t(model.name)}</h2><span className="publisher">{t(model.publisher)}</span><p>{t(model.description)}</p><div className="tag-list">{model.tags.map(tag=><span key={tag}>{t(tag)}</span>)}</div><div className="card-bottom">{t('查看详情')}<ArrowRight size={15}/></div></button>)}</div>{!visible.length&&<div className="empty-state"><h2>{t('没有找到相关模型')}</h2><p>{t('调整关键词或筛选条件再试试。')}</p><button className="secondary-button" onClick={()=>setView({...view,query:'',filter:'all'})}>{t('清除筛选')}</button></div>}<p className="catalog-footnote">{t('这里不会自动下载模型，也不会发送你的项目资料。')}</p>
 {detail&&<Modal title={t(detail.name)} close={()=>setDetail(null)}><span className={`model-avatar ${detail.color}`}>{detail.initials}</span><p>{t(detail.description)}</p><div className="info-box">{t(detail.details)}</div><div className="detail-row"><span>{t('下载与运行')}</span><strong>{t('尚未接入')}</strong></div><button className="primary-button full" onClick={()=>{setDetail(null);choose(detail);}}>{t('用于草稿偏好')}<ArrowRight size={15}/></button></Modal>}
 </div>;
}
export function CapabilityCatalogPage({directory,view,setView,useTemplate,onTabChange}:{directory:CatalogDirectory;view:CapabilityView;setView:Dispatch<SetStateAction<CapabilityView>>;useTemplate(skill:Capability):void;onTabChange?(tab:CapabilityView['tab']):void}){
 const [skill,setSkill]=useState<Capability|null>(null);const [plugin,setPlugin]=useState<PluginListing|null>(null);const id=useId();
 const current=view[view.tab];const setFilter=(update:Partial<typeof current>)=>setView(old=>({...old,[old.tab]:{...old[old.tab],...update}}));
 const skills=directory.data.skills.filter(s=>matches(current.query,s.name,s.description)&&(current.category==='all'||s.categoryId===current.category));
 const plugins=directory.data.plugins.filter(p=>matches(current.query,p.name,p.description,p.publisher)&&(current.category==='all'||p.category===current.category));
 const switchTab=(tab:CapabilityView['tab'])=>{setSkill(null);setPlugin(null);setView(old=>({...old,tab}));onTabChange?.(tab);};
 return <div className="content-page catalog-page"><div className="page-heading"><div><div className="eyebrow">MADE FOR YOUR WORK</div><h1>{t('让助手，多一点本领')}</h1><p className="page-description">{t('把工具、模型与工作方式，组合成适合你的能力。')}</p></div><div className="heading-illustration purple"><Puzzle size={42} strokeWidth={1}/></div></div><div className="catalog-tabs" role="tablist" aria-label={t('能力类型')}>{(['skills','plugins'] as const).map(tab=><button key={tab} id={`${id}-${tab}`} role="tab" aria-selected={view.tab===tab} aria-controls={`${id}-panel`} tabIndex={view.tab===tab?0:-1} onClick={()=>switchTab(tab)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'skills':e.key==='End'?'plugins':view.tab==='skills'?'plugins':'skills';switchTab(next);document.getElementById(`${id}-${next}`)?.focus();}}}>{tab==='skills'?<BookOpen size={16}/>:<Puzzle size={16}/>} {t(tab==='skills'?'技能':'插件')}</button>)}</div><DirectoryStatus directory={directory}/><div id={`${id}-panel`} role="tabpanel" aria-labelledby={`${id}-${view.tab}`}><div className="catalog-controls"><div className="segments" aria-label={t('能力筛选')}>{[{id:'all',label:'全部'},...directory.data.categories].map(c=><button key={c.id} aria-pressed={current.category===c.id} className={current.category===c.id?'selected':''} onClick={()=>setFilter({category:c.id})}>{t(c.label)}</button>)}</div><label className="search-field"><Search size={16}/><input type="search" aria-label={t('搜索能力')} placeholder={t('搜索工作能力')} value={current.query} onChange={e=>setFilter({query:e.target.value})}/></label></div>
 {view.tab==='skills'?<><SkillManager query={current.query}/><h2>{t('内置任务模板')}</h2><div className="plugin-list">{skills.map(cap=>{const Icon=icons[cap.icon];return <button className="plugin-card skill-card surface-card" key={cap.id} onClick={()=>setSkill(cap)}><span className={`cap-icon large ${cap.color}`}><Icon size={26}/></span><div><h2>{t(cap.name)}<span className="badge neutral">{t('内置模板')}</span></h2><p>{t(cap.description)}</p><small>Ambleloft · {t(cap.category)}</small></div><ChevronRight size={18}/></button>;})}</div>{!skills.length&&<div className="empty-state"><h2>{t('没有找到相关能力')}</h2><p>{t('试试其他分类或关键词。')}</p><button className="secondary-button" onClick={()=>setFilter({query:'',category:'all'})}>{t('清除筛选')}</button></div>}<p className="catalog-footnote">{t('内置模板用于快速填写任务；我的技能支持导入、维护和按需调用。')}</p></>:<><div className="plugin-list">{plugins.map(p=><button className="plugin-card surface-card" key={p.id} onClick={()=>setPlugin(p)}><span className="cap-icon large purple"><Puzzle size={26}/></span><div><h2>{t(p.name)}<span className="badge neutral">{t('目录预览')}</span></h2><p>{t(p.description)}</p><small>{p.publisher} · {p.version}</small></div><ChevronRight size={18}/></button>)}</div>{!plugins.length&&<div className="empty-state surface-card plugin-empty"><Puzzle size={32}/><h2>{t(directory.data.plugins.length?'没有找到相关能力':'插件目录正在准备中')}</h2><p>{t(directory.data.plugins.length?'试试其他分类或关键词。':'插件将提供工具、应用连接与内容渲染等能力。当前没有可安装条目。')}</p>{(current.query||current.category!=='all')&&<button className="secondary-button" onClick={()=>setFilter({query:'',category:'all'})}>{t('清除筛选')}</button>}</div>}</>}
 </div>
 {skill&&<Modal title={t(skill.name)} close={()=>setSkill(null)}><p>{t(skill.description)}</p><span className="badge neutral">{t('官方内置任务模板')}</span><h3 className="modal-section-title">{t('未来执行时所需权限')}</h3><ul className="permission-list">{skill.permissions.map(p=><li key={p}><ShieldCheck size={15}/>{t(p)}</li>)}</ul><div className="info-box">{t('使用模板只会填入任务内容，不会安装插件或授予文件访问权限。')}</div><button className="primary-button full" onClick={()=>{setSkill(null);useTemplate(skill);}}>{t('使用模板')}<ArrowRight size={15}/></button></Modal>}
 {plugin&&<Modal title={t(plugin.name)} close={()=>setPlugin(null)}><p>{t(plugin.description)}</p><p>{plugin.publisher} · {plugin.version}</p><h3>{t('包含的技能')}</h3><ul>{plugin.skillIds.map(id=><li key={id}>{t(directory.data.skills.find(s=>s.id===id)?.name||id)}</li>)}</ul><h3>{t('未来执行时所需权限')}</h3><ul>{plugin.permissions.map(p=><li key={p}>{t(p)}</li>)}</ul><p className="info-box">{t('尚未接入')}</p></Modal>}
 </div>;
}
