import {Button} from './components/ui/button';
import ExtensionOperationDialog from './ExtensionOperationDialog';
import {useEffect,useState} from 'react';import Modal from './Modal';import {t} from './i18n';import type {ExtensionInteractionRequest} from './types';
export default function ExtensionInteraction(){
 const [remember,setRemember]=useState(false);
 const [request,setRequest]=useState<ExtensionInteractionRequest|null>(null),[projectId,setProjectId]=useState(''),[value,setValue]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const api=window.desktop?.extensionPage;if(!api)return;const open=api.onInteraction(r=>{setRemember(false);setProjectId('');setValue('');setError('');setBusy(false);setRequest(r);}),close=api.onInteractionClose(id=>{setRequest(current=>current?.id===id?null:current);setValue('');});return()=>{open();close();};},[]);
 if(!request)return null;
 const submit=async(cancel=false)=>{setBusy(true);setError('');try{await window.desktop!.extensionPage!.respond({id:request.id,cancel,projectId,value,remember});setValue('');setRequest(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 if(request.kind==='operation')return <ExtensionOperationDialog request={request} remember={remember} setRemember={setRemember} busy={busy} error={error} submit={submit}/>;
 return <Modal title={request.kind==='operation'?t('确认扩展操作'):t('允许扩展访问')} busy={busy} close={()=>void submit(true)}><form className="project-editor" onSubmit={e=>{e.preventDefault();void submit();}}><p className="fine-print">{request.extensionName}</p>{request.kind!=='operation'&&<p>{request.capabilities.join(' · ')}</p>}{request.kind==='selectProject'&&<label>{t('选择授权项目')}<select aria-label={t('选择授权项目')} value={projectId} onChange={e=>setProjectId(e.target.value)} required><option value="">{t('请选择项目')}</option>{request.projects?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}{request.kind==='requestGrant'&&<p>{t('项目')}：{request.project}</p>}{request.kind==='requestSecretInput'&&<label>{request.title}<input type="password" aria-label={t('扩展凭据')} autoComplete="off" value={value} onChange={e=>setValue(e.target.value)} maxLength={16000} required/></label>}{request.kind!=='operation'&&<p className="fine-print">{t('由 Amblelost 确认你的选择。填写的登录信息不会显示在扩展页面中。')}</p>}{error&&<p role="alert">{error}</p>}<div className="modal-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>void submit(true)}>{t('取消')}</Button><Button type="submit" variant="default" disabled={busy||(request.kind==='selectProject'&&!projectId)||(request.kind==='requestSecretInput'&&!value)}>{t(request.kind==='operation'?'确认执行':'确认授权')}</Button></div></form></Modal>;
}
