import {useConfirm} from './Confirmation';
import {Button} from './components/ui/button';
import {Input} from './components/ui/input';
import {Textarea} from './components/ui/textarea';
import {Separator} from './components/ui/separator';
import {Switch} from './components/ui/switch';
import {NativeSelect,NativeSelectOption} from './components/ui/native-select';
import {Field,FieldContent,FieldGroup,FieldLabel,FieldDescription} from './components/ui/field';
import {useEffect,useState,useId,useRef} from 'react';
import Modal from './Modal';
import {t} from './i18n';
import type {ConfigurationSchema,ExtensionConfiguration} from './types';
export default function ExtensionSettings({id,name,close,inline=false,onDirtyChange,generation}:{id:string;generation?:number;name:string;close:()=>void;inline?:boolean;onDirtyChange?(dirty:boolean):void}){
 const confirm=useConfirm();
 const fieldPrefix=useId();
 const [data,setData]=useState<ExtensionConfiguration|null>(null),[value,setValue]=useState<Record<string,unknown>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
 const dirtyRef=useRef(dirty);dirtyRef.current=dirty;
 const accept=(next:ExtensionConfiguration)=>{setData(next);setValue(next.value);setDirty(false);};
 const reload=async()=>{if(dirtyRef.current&&!(await confirm({title:t('放弃未保存的修改？'),action:t('放弃修改'),destructive:true})))return;try{accept(await window.desktop!.extensions!.configuration({id}));setError('');}catch(e){setError((e as Error).message);}};
 useEffect(()=>{let alive=true;if(dirtyRef.current){setError(t('扩展授权已变化。当前修改已保留，请重新加载配置后再保存。'));return;}setError('');window.desktop!.extensions!.configuration({id}).then(v=>{if(alive)accept(v);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[id,generation]);
 useEffect(()=>{onDirtyChange?.(dirty);},[dirty,onDirtyChange]);
 const dismiss=async()=>{if(!dirty||(await confirm({title:t('放弃未保存的修改？'),action:t('放弃修改'),destructive:true})))close();};
 const submit=async(action:'save'|'reset')=>{if(!data)return;setBusy(true);setError('');try{accept(await window.desktop!.extensions!.configuration({id,action,value,generation:data.generation,expectedRevision:data.revision}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const field=(key:string,s:ConfigurationSchema,required:boolean)=>{const current=value[key];const change=(v:unknown)=>{setValue(old=>({...old,[key]:v}));setDirty(true);};const controlId=fieldPrefix+'-'+key;const isSwitch=s.type==='boolean'&&!s.enum;return <Field key={key} className="extension-config-field" orientation={isSwitch?'horizontal':'vertical'} data-disabled={busy}><FieldContent className="min-w-0"><FieldLabel htmlFor={controlId}>{key}{required?' *':''}</FieldLabel>{s.description&&<FieldDescription id={controlId+'-description'}>{s.description}</FieldDescription>}</FieldContent><div className={isSwitch?'shrink-0':'min-w-0 w-full'}>{s.enum?<NativeSelect id={controlId} aria-describedby={s.description?controlId+'-description':undefined} className="w-full [&_select]:max-w-none" disabled={busy} value={current===undefined?'':JSON.stringify(current)} onChange={e=>change(JSON.parse(e.target.value))} required={required}><NativeSelectOption value="" disabled>{t('请选择')}</NativeSelectOption>{s.enum.map(v=><NativeSelectOption key={JSON.stringify(v)} value={JSON.stringify(v)}>{String(v)}</NativeSelectOption>)}</NativeSelect>:s.type==='boolean'?<Switch id={controlId} aria-describedby={s.description?controlId+'-description':undefined} disabled={busy} checked={current===true} onCheckedChange={change}/>:['string','number','integer'].includes(s.type)?<Input id={controlId} aria-describedby={s.description?controlId+'-description':undefined} disabled={busy} required={required} type={s.type==='string'?'text':'number'} step={s.type==='integer'?1:'any'} min={s.minimum} max={s.maximum} minLength={s.minLength} maxLength={s.maxLength} value={current===undefined?'':String(current)} onChange={e=>{if(e.target.value===''){setValue(old=>{const next={...old};delete next[key];return next;});setDirty(true);}else change(s.type==='string'?e.target.value:Number(e.target.value));}}/>:<Textarea id={controlId} aria-describedby={s.description?controlId+'-description':undefined} key={data?.revision} disabled={busy} defaultValue={JSON.stringify(current??(s.type==='array'?[]:s.type==='null'?null:{}),null,2)} onChange={e=>{setDirty(true);try{change(JSON.parse(e.target.value));e.target.setCustomValidity('');}catch{e.target.setCustomValidity(t('请输入有效的 JSON'));}}}/>}</div></Field>;};
 const form=<form className="extension-config-form flex w-full min-w-0 max-w-xl flex-col gap-6" onSubmit={e=>{e.preventDefault();void submit('save');}}>{error&&<div><p className="error-banner" role="alert">{error}</p><Button type="button" variant="outline" disabled={busy} onClick={()=>void reload()}>{t('重新加载配置')}</Button></div>}{!data&&!error&&<p>{t('正在加载…')}</p>}{data&&<>{data.schema.description&&<p>{data.schema.description}</p>}<FieldGroup className="gap-6">{Object.entries(data.schema.properties||{}).map(([key,s])=>field(key,s,data.schema.required?.includes(key)||false))}</FieldGroup><Separator/><div className="extension-config-actions"><Button type="button" variant="outline" disabled={busy} onClick={async()=>{if(await confirm({title:t('恢复默认值'),description:t('清除已保存的配置，恢复扩展默认行为？'),action:t('恢复默认值'),destructive:true}))void submit('reset');}}>{t('恢复默认值')}</Button><div className="extension-config-save"><span role="status" aria-live="polite">{t(busy?'正在保存…':dirty?'有未保存的修改':'已保存')}</span><Button type="submit" disabled={busy||!dirty}>{t('保存配置')}</Button></div></div></>}</form>;
 return inline?form:<Modal title={name+' · '+t('扩展设置')} close={dismiss} busy={busy}>{form}</Modal>;
}
