import ArchivedConversations from './ArchivedConversations';
import ExtensionsPage from './ExtensionsPage';
import { t } from './i18n';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft, Settings, MessageCircle, PlugZap, Puzzle, BookOpen, Compass, Database, Box, SlidersHorizontal, Cpu, Cloud, Monitor, Sun, Moon, Check, Type, Languages, ShieldCheck, Info, Plus} from 'lucide-react';
import type {Workspace, ProviderConfig, ProviderCatalog} from './types';
import type {NavTask} from './WorkspaceNavigation';
import SkillManager from './SkillManager';
import ProviderSettings from './ProviderSettings';
export const settingsGroups=[
 {name:'设置',items:[{id:'general',label:'通用',icon:Settings},{id:'conversations',label:'会话',icon:MessageCircle}]},
 {name:'集成',items:[{id:'apps',label:'已连接的应用',icon:PlugZap},{id:'plugins',label:'扩展',icon:Puzzle},{id:'skills',label:'技能',icon:BookOpen}]},
 {name:'模型服务',items:[{id:'providers',label:'模型提供商',icon:Cloud}]},
];
export default function SettingsWorkspace({section,setSection,workspace,save,back,archived,restore,remove,catalog,refresh,busy}:{section:string;setSection(value:string):void;workspace:Workspace;save(update:Partial<Workspace>):Promise<void>;back():void;archived:NavTask[];restore(task:NavTask):Promise<void>;remove(task:NavTask):Promise<void>;catalog:ProviderCatalog;refresh():Promise<void>;busy:boolean}){
 const backRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{backRef.current?.focus({preventScroll:true});},[]);
 const [editor,setEditor]=useState<ProviderConfig|null|undefined>();
 const [pending,setPending]=useState(false);const [error,setError]=useState('');const [deleting,setDeleting]=useState<string|null>(null);const [result,setResult]=useState<Record<string,string>>({});
 const act=async(fn:()=>Promise<unknown>)=>{setPending(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setPending(false);}};
 const change=(fn:()=>void)=>{if(editor!==undefined&&!window.confirm(t('离开模型编辑？未保存的修改将丢失。')))return;setEditor(undefined);setDeleting(null);setError('');fn();};
 const label=settingsGroups.flatMap(g=>g.items).find(i=>i.id===section)?.label||'通用';
 return <div className="settings-workspace" aria-label={t("设置工作区")}><aside className="settings-sidebar"><div className="settings-return"><button ref={backRef} className="secondary-button" onClick={()=>change(back)}><ArrowLeft size={16}/>{t("返回应用")}</button></div><nav aria-label={t("设置导航")}>{settingsGroups.map(group=><section key={t(group.name)}><h2>{t(group.name)}</h2>{group.items.map(item=><button key={item.id} className={`nav-item ${section===item.id?'active':''}`} aria-current={section===item.id?'page':undefined} onClick={()=>change(()=>setSection(item.id))}><item.icon size={17}/><span>{t(item.label)}</span></button>)}</section>)}</nav></aside><div className="settings-main"><header className="toolbar"><strong>{t(label)}</strong></header><main className="settings-content" key={section}>
 {error&&<div className="error-banner" role="alert">{error}</div>}
 {section==='general'&&<><div className="eyebrow">MAKE IT YOURS</div><h1>{t("舒服地，开始工作")}</h1><p className="page-description">{t("简单的设置，适合你的习惯。")}</p>
 <section className="settings-group"><h2><Languages size={18}/>{t("语言")}</h2><div className="setting-row"><span>{t("界面语言")}<small>{t("不改变会话内容或模型回答语言。")}</small></span><select aria-label={t("界面语言")} value={workspace.language||'zh-CN'} disabled={busy||pending} onChange={e=>void act(()=>save({language:e.target.value as Workspace['language']}))}><option value="system">{t("跟随系统")}</option><option value="zh-CN">{t("简体中文")}</option><option value="en">English</option></select></div></section>
 <section className="settings-group font-size-setting"><h2><Type size={18}/>{t('字体大小')}</h2><div className="setting-row"><span>{t('调整界面和阅读文字大小')}<small>{t('立即生效，不改变文档本身的格式。')}</small></span><button className="text-button" disabled={busy||pending||(workspace.fontScale||100)===100} onClick={()=>void act(()=>save({fontScale:100}))}>{t('恢复默认')}</button></div><div className="font-size-control"><input type="range" min="90" max="130" step="10" aria-label={t('字体大小')} aria-valuetext={`${workspace.fontScale||100}%${(workspace.fontScale||100)===100?' · '+t('默认'):''}`} value={workspace.fontScale||100} disabled={busy||pending} onChange={event=>void act(()=>save({fontScale:Number(event.target.value)}))}/><output>{workspace.fontScale||100}%</output></div><div className="font-size-labels"><span>{t('较小')}</span><span>{t('默认')} · 100%</span><span>{t('较大')}</span></div></section>
 <section className="settings-group"><h2><Monitor size={18}/>{t("外观")}</h2><p>{t("默认跟随系统，也可以选择你喜欢的模式。")}</p><div className="theme-options">{([{id:'system',label:'跟随系统',icon:Monitor},{id:'light',label:'浅色',icon:Sun},{id:'dark',label:'深色',icon:Moon}] as const).map(theme=><button key={theme.id} disabled={busy||pending} aria-pressed={workspace.theme===theme.id} className={`theme-option ${workspace.theme===theme.id?'selected':''}`} onClick={()=>void act(()=>save({theme:theme.id}))}><theme.icon size={23}/><span>{t(theme.label)}</span>{workspace.theme===theme.id&&<Check size={15}/>}</button>)}</div></section>
 <section className="settings-group"><h2><ShieldCheck size={18}/>{t("数据与隐私")}</h2><div className="setting-row"><span><strong>{t("工作台数据")}</strong><small>{t("会话和设置保存在本机，服务密钥使用系统加密存储。")}</small></span><span className="badge green">{t("本地保存")}</span></div><div className="setting-row"><span><strong>{t("云端与模型调用")}</strong><small>{t("任务及所用上下文仅发送至该会话绑定的模型服务。")}</small></span></div></section>
 <section className="settings-group"><h2><Info size={18}/>{t("关于 Ambleloft")}</h2><p>{t("v0.2.1 · 桌面预览")}</p><p>{t("你的个人 AI 工作台。支持模型服务、多轮对话与执行审批。")}</p></section></>}
 {section==='conversations'&&<ArchivedConversations tasks={archived} projects={workspace.projects} restore={restore} remove={remove}/>}
 {section==='providers'&&<><div className="section-heading"><h1>{t("模型提供商")}</h1><button className="primary-button" disabled={!window.desktop||pending} onClick={()=>change(()=>setEditor(null))}><Plus size={16}/>{t("添加服务")}</button></div><p className="page-description">{t("连接多个模型服务。默认设置用于新任务，已有会话保留原来的服务和模型。")}</p>{editor!==undefined?<><button className="text-button" onClick={()=>change(()=>{})}>{t("返回服务列表")}</button><ProviderSettings key={editor?.id||'new'} config={editor} onSaved={()=>{setEditor(undefined);setResult({});void act(refresh);}}/></>:<>{!catalog.providers.length&&<section className="settings-group"><p>{t("尚未配置模型服务。")}{!window.desktop&&'请在桌面版中添加服务。'}</p></section>}{catalog.providers.map(provider=><section className="settings-group provider-card" key={provider.id}><div className="section-heading"><h2>{provider.name||provider.model}</h2>{provider.id===catalog.defaultId&&<span className="badge green">{t("默认服务")}</span>}</div><p className="provider-url">{provider.baseUrl}</p><p>{(provider.models||[provider.model]).join(' · ')}</p><small>{provider.hasKey?t("密钥已加密保存"):t("未设置密钥")}{t("· 默认模型：")}{provider.model}</small><div className="settings-actions"><button className="secondary-button" onClick={()=>setEditor(provider)}>{t("编辑")}</button><button className="secondary-button" disabled={pending} onClick={()=>void act(async()=>{setResult(current=>({...current,[provider.id!]:''}));const response=await window.desktop!.testProvider(provider.id);setResult({...result,[provider.id!]:response.message});})}>{t("测试连接")}</button>{provider.id!==catalog.defaultId&&<button className="text-button" disabled={pending} onClick={()=>void act(async()=>{await window.desktop!.setDefaultProvider(provider.id!);await refresh();})}>{t("设为默认")}</button>}<button className="text-button danger" disabled={pending} onClick={()=>setDeleting(provider.id!)}>{t("删除服务")}</button></div>{result[provider.id!]&&<p role="status">{result[provider.id!]}</p>}{deleting===provider.id&&<div className="delete-confirm"><p>{t("删除此服务配置和已保存密钥？仍被会话引用的服务不能删除。")}</p><button className="secondary-button" onClick={()=>setDeleting(null)}>{t("取消")}</button><button className="danger-button" disabled={pending} onClick={()=>void act(async()=>{await window.desktop!.removeProvider(provider.id!);await refresh();setDeleting(null);})}>{t("确认删除服务")}</button></div>}</section>)}</>}</>}
 {section==='plugins'&&<ExtensionsPage/>}
 {section==='skills'&&<SkillManager query=""/>}
 {section==='apps'&&<><h1>{t(label)}</h1><section className="settings-group"><p>{t("在这里管理已连接的应用与访问权限。")}</p><p className="fine-print">连接器将通过扩展提供，当前尚未接入。</p></section></>}

 </main></div></div>;
}
