import { t } from './i18n';
import {useEffect,useRef,useState,type Dispatch,type SetStateAction} from 'react';
import {ArrowLeft, Settings, MessageCircle, PlugZap, Puzzle, BookOpen, Compass, Database, Box, SlidersHorizontal, Cpu, Cloud, Monitor, Sun, Moon, Check, Languages, ShieldCheck, Info, Plus} from 'lucide-react';
import type {Workspace, ProviderConfig, ProviderCatalog} from './types';
import type {NavTask} from './WorkspaceNavigation';
import {ModelCatalogPage,CapabilityCatalogPage,type ModelView,type CapabilityView} from './CatalogPages';
import type {CatalogDirectory} from './catalog-service';
import type {Capability,Model} from './types';
import ProviderSettings from './ProviderSettings';
export const settingsGroups=[
 {name:'设置',items:[{id:'general',label:'通用',icon:Settings},{id:'conversations',label:'会话',icon:MessageCircle}]},
 {name:'集成',items:[{id:'apps',label:'已连接的应用',icon:PlugZap},{id:'plugins',label:'插件',icon:Puzzle},{id:'skills',label:'技能',icon:BookOpen}]},
 {name:'本地模型',items:[{id:'explore',label:'探索',icon:Compass},{id:'library',label:'资源库',icon:Database},{id:'instances',label:'已加载的实例',icon:Box},{id:'defaults',label:'本地模型默认设置',icon:SlidersHorizontal},{id:'runtime',label:'运行时',icon:Cpu}]},
 {name:'自定义模型',items:[{id:'providers',label:'模型提供商',icon:Cloud}]},
];
export default function SettingsWorkspace({section,setSection,workspace,save,back,archived,restore,remove,catalog,refresh,busy,directory,modelView,setModelView,capabilityView,setCapabilityView,chooseModel,useTemplate}:{section:string;setSection(value:string):void;workspace:Workspace;save(update:Partial<Workspace>):Promise<void>;back():void;archived:NavTask[];restore(task:NavTask):Promise<void>;remove(task:NavTask):Promise<void>;catalog:ProviderCatalog;refresh():Promise<void>;busy:boolean;directory:CatalogDirectory;modelView:ModelView;setModelView:Dispatch<SetStateAction<ModelView>>;capabilityView:CapabilityView;setCapabilityView:Dispatch<SetStateAction<CapabilityView>>;chooseModel(model:Model):void;useTemplate(skill:Capability):void}){
 const backRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{backRef.current?.focus({preventScroll:true});},[]);
 const [editor,setEditor]=useState<ProviderConfig|null|undefined>();
 const [pending,setPending]=useState(false);const [error,setError]=useState('');const [deleting,setDeleting]=useState<string|null>(null);const [result,setResult]=useState<Record<string,string>>({});
 const act=async(fn:()=>Promise<unknown>)=>{setPending(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setPending(false);}};
 const change=(fn:()=>void)=>{if(editor!==undefined&&!window.confirm(t('离开模型编辑？未保存的修改将丢失。')))return;setEditor(undefined);setDeleting(null);setError('');fn();};
 const label=settingsGroups.flatMap(g=>g.items).find(i=>i.id===section)?.label||'通用';
 return <div className="settings-workspace" aria-label={t("设置工作区")}><aside className="settings-sidebar"><div className="settings-return"><button ref={backRef} className="secondary-button" onClick={()=>change(back)}><ArrowLeft size={16}/>{t("返回应用")}</button></div><nav aria-label={t("设置导航")}>{settingsGroups.map(group=><section key={t(group.name)}><h2>{t(group.name)}</h2>{group.items.map(item=><button key={item.id} className={`nav-item ${section===item.id?'active':''}`} aria-current={section===item.id?'page':undefined} onClick={()=>change(()=>setSection(item.id))}><item.icon size={17}/><span>{t(item.label)}</span></button>)}</section>)}</nav></aside><div className="settings-main"><header className="toolbar"><strong>{t(label)}</strong></header><main className="settings-content" key={section}>
 {error&&<div className="error-banner" role="alert">{error}</div>}
 {section==='general'&&<><div className="eyebrow">MAKE IT YOURS</div><h1>{t("舒服地，开始工作")}</h1><p className="page-description">{t("简单的设置，适合你的习惯。")}</p>
 <section className="settings-group"><h2><Languages size={18}/>{t("语言")}</h2><div className="setting-row"><span>{t("界面语言")}<small>{t("不改变会话内容或模型回答语言。")}</small></span><select aria-label={t("界面语言")} value={workspace.language||'zh-CN'} disabled={busy||pending} onChange={e=>void act(()=>save({language:e.target.value as Workspace['language']}))}><option value="system">{t("跟随系统")}</option><option value="zh-CN">{t("简体中文")}</option><option value="en">English</option></select></div></section>
 <section className="settings-group"><h2><Monitor size={18}/>{t("外观")}</h2><p>{t("默认跟随系统，也可以选择你喜欢的模式。")}</p><div className="theme-options">{([{id:'system',label:'跟随系统',icon:Monitor},{id:'light',label:'浅色',icon:Sun},{id:'dark',label:'深色',icon:Moon}] as const).map(theme=><button key={theme.id} disabled={busy||pending} aria-pressed={workspace.theme===theme.id} className={`theme-option ${workspace.theme===theme.id?'selected':''}`} onClick={()=>void act(()=>save({theme:theme.id}))}><theme.icon size={23}/><span>{t(theme.label)}</span>{workspace.theme===theme.id&&<Check size={15}/>}</button>)}</div></section>
 <section className="settings-group"><h2><ShieldCheck size={18}/>{t("数据与隐私")}</h2><div className="setting-row"><span><strong>{t("工作台数据")}</strong><small>{t("会话和设置保存在本机，服务密钥使用系统加密存储。")}</small></span><span className="badge green">{t("本地保存")}</span></div><div className="setting-row"><span><strong>{t("云端与模型调用")}</strong><small>{t("任务及所用上下文仅发送至该会话绑定的模型服务。")}</small></span></div></section>
 <section className="settings-group"><h2><Info size={18}/>{t("关于 Ambleloft")}</h2><p>{t("v0.2.1 · 桌面预览")}</p><p>{t("你的个人 AI 工作台。支持模型服务、多轮对话与执行审批。")}</p></section></>}
 {section==='conversations'&&<><h1>{t("已归档会话")}</h1><p className="page-description">{t("还原后继续工作，或永久删除不再需要的记录。")}</p><section className="settings-group archive-list">{!archived.length?<p>{t("暂无已归档会话。")}</p>:archived.map(task=><div className="archive-row" key={task.id}><div><strong>{task.title}</strong><small>{workspace.projects.find(p=>p.id===task.projectId)?.name||'未关联项目'} · {new Date(task.archivedAt!).toLocaleDateString()} {task.draft?t("· 草稿"):''}</small></div><button className="secondary-button" disabled={pending} onClick={()=>void act(()=>restore(task))}>{t("还原")}</button><button className="text-button danger" disabled={pending} onClick={()=>setDeleting(task.id)}>{t("永久删除")}</button>{deleting===task.id&&<div className="delete-confirm"><p>{t("永久删除这条会话？无法撤销，不删除本机文件。")}</p><button className="secondary-button" onClick={()=>setDeleting(null)}>{t("取消")}</button><button className="danger-button" disabled={pending} onClick={()=>void act(async()=>{await remove(task);setDeleting(null);})}>{t("确认永久删除")}</button></div>}</div>)}</section></>}
 {section==='providers'&&<><div className="section-heading"><h1>{t("模型提供商")}</h1><button className="primary-button" disabled={!window.desktop||pending} onClick={()=>change(()=>setEditor(null))}><Plus size={16}/>{t("添加服务")}</button></div><p className="page-description">{t("连接多个模型服务。默认设置用于新任务，已有会话保留原来的服务和模型。")}</p>{editor!==undefined?<><button className="text-button" onClick={()=>change(()=>{})}>{t("返回服务列表")}</button><ProviderSettings key={editor?.id||'new'} config={editor} onSaved={()=>{setEditor(undefined);setResult({});void act(refresh);}}/></>:<>{!catalog.providers.length&&<section className="settings-group"><p>{t("尚未配置模型服务。")}{!window.desktop&&'请在桌面版中添加服务。'}</p></section>}{catalog.providers.map(provider=><section className="settings-group provider-card" key={provider.id}><div className="section-heading"><h2>{provider.name||provider.model}</h2>{provider.id===catalog.defaultId&&<span className="badge green">{t("默认服务")}</span>}</div><p className="provider-url">{provider.baseUrl}</p><p>{(provider.models||[provider.model]).join(' · ')}</p><small>{provider.hasKey?t("密钥已加密保存"):t("未设置密钥")}{t("· 默认模型：")}{provider.model}</small><div className="settings-actions"><button className="secondary-button" onClick={()=>setEditor(provider)}>{t("编辑")}</button><button className="secondary-button" disabled={pending} onClick={()=>void act(async()=>{setResult(current=>({...current,[provider.id!]:''}));const response=await window.desktop!.testProvider(provider.id);setResult({...result,[provider.id!]:response.message});})}>{t("测试连接")}</button>{provider.id!==catalog.defaultId&&<button className="text-button" disabled={pending} onClick={()=>void act(async()=>{await window.desktop!.setDefaultProvider(provider.id!);await refresh();})}>{t("设为默认")}</button>}<button className="text-button danger" disabled={pending} onClick={()=>setDeleting(provider.id!)}>{t("删除服务")}</button></div>{result[provider.id!]&&<p role="status">{result[provider.id!]}</p>}{deleting===provider.id&&<div className="delete-confirm"><p>{t("删除此服务配置和已保存密钥？仍被会话引用的服务不能删除。")}</p><button className="secondary-button" onClick={()=>setDeleting(null)}>{t("取消")}</button><button className="danger-button" disabled={pending} onClick={()=>void act(async()=>{await window.desktop!.removeProvider(provider.id!);await refresh();setDeleting(null);})}>{t("确认删除服务")}</button></div>}</section>)}</>}</>}
 {section==='explore'&&<ModelCatalogPage directory={directory} view={modelView} setView={setModelView} choose={chooseModel}/>}
 {['skills','plugins'].includes(section)&&<CapabilityCatalogPage directory={directory} view={{...capabilityView,tab:section==='plugins'?'plugins':'skills'}} setView={update=>setCapabilityView(old=>{const current={...old,tab:section==='plugins'?'plugins' as const:'skills' as const};return typeof update==='function'?update(current):update;})} useTemplate={useTemplate} onTabChange={setSection}/>}
 {!['general','conversations','providers','explore','skills','plugins'].includes(section)&&<><h1>{t(label)}</h1><p className="page-description">{t("为你的工作台扩展更多能力。")}</p><section className="settings-group"><h2>{t(label)}</h2><span className="badge neutral">{t("后续开放")}</span><p>{section==='apps'?t("在这里管理已连接的应用与访问权限。"):section==='plugins'?t("在这里管理插件安装与启用状态。"):section==='skills'?t("在这里管理可复用的技能与工作方式。"):section==='explore'?t("在这里发现适合设备的本地模型。"):section==='library'?t("在这里管理已下载的模型文件。"):section==='instances'?t("在这里查看和管理正在运行的模型。"):section==='defaults'?t("在这里设置本地模型的默认运行参数。"):t("在这里管理本地推理引擎与运行环境。")}</p><p className="fine-print">{t("本次先提供导航结构，具体功能将在后续版本设计与接入。")}</p></section></>}
 </main></div></div>;
}
