import {Empty,EmptyHeader,EmptyMedia,EmptyTitle,EmptyDescription} from './components/ui/empty';
import './sidebar-layout.css';
import {SidebarContent,SidebarGroup,SidebarGroupLabel,SidebarGroupAction,SidebarGroupContent,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarMenuAction,SidebarMenuSub} from './components/ui/sidebar';
import {Collapsible,CollapsibleContent} from './components/ui/collapsible';
import {Button} from './components/ui/button';
import {ProjectInfo} from './ProjectInfo';
import VirtualBlock from './VirtualBlock';
import ProjectCategoryIcon from './ProjectCategoryIcon';
import ExtensionCategoryIcon from './ExtensionCategoryIcon';
import { t, useLanguage } from './i18n';
import { useEffect, useLayoutEffect, useRef, useState, type ReactNode } from 'react';
import {Popover,PopoverContent} from './components/ui/popover';
import { ChevronRight, Folder, SquarePen, MoreHorizontal, Plus, MessageCircle, Settings } from 'lucide-react';
import type { AgentRun, Project, Task } from './types';
import { runStatus } from './Conversation';
export type NavTask = {revision?:number;unread?:boolean;queued?:boolean;questions?:AgentRun["questions"];archivedAt?:string|null;id:string; title:string; projectId:string|null; createdAt:string; updatedAt?:string; status:string; draft?:boolean};
export function workspaceTasks(runs:AgentRun[], drafts:Task[], projects:Project[]):NavTask[] {
 // Streaming updates change updatedAt on every event; only a new turn should reorder tasks.
 const orderedRuns=runs.map(run=>({...run,updatedAt:run.messages?.findLast(message=>message.role==='user')?.timing?.startedAt||run.lastTurnStartedAt||run.createdAt}));
 return [...orderedRuns,...drafts.map(task=>({...task,draft:true}))].map<NavTask>(task=>({...task,projectId:projects.some(p=>p.id===task.projectId)?task.projectId:null})).sort((a,b)=>(b.updatedAt||b.createdAt).localeCompare(a.updatedAt||a.createdAt));
}
export default function WorkspaceNavigation({hasExtensions=true,activeGroup,extensionsContent,manageExtensions,projects,tasks,selected,projectId,open,newTask,openProject,editProject,editTask,addProject}:{hasExtensions?:boolean;activeGroup?:'projects'|'chats'|'extensions';extensionsContent?:ReactNode;manageExtensions():void;projects:Project[];tasks:NavTask[];selected:string|null;projectId:string;open(task:NavTask):void;newTask(project?:string):void;openProject(id:string):void;editProject(project:Project):void;editTask(task:NavTask):void;addProject():void}) {
 useLanguage();
 const scrollPositions=useRef<Record<string,number>>({});
 const contentRef=useRef<HTMLDivElement>(null);
 useLayoutEffect(()=>{const el=contentRef.current;if(el)el.scrollTop=scrollPositions.current[activeGroup||'all']||0;},[activeGroup]);
 const [limits,setLimits]=useState<Record<string,number>>({});
 const [projectLimit,setProjectLimit]=useState(30);
 const dateGroup=(task:NavTask)=>{const date=new Date(task.updatedAt||task.createdAt);const today=new Date();today.setHours(0,0,0,0);const yesterday=new Date(today);yesterday.setDate(yesterday.getDate()-1);const week=new Date(today);week.setDate(week.getDate()-6);return date>=today?'今天':date>=yesterday?'昨天':date>=week?'近 7 天':'更早';};
 const empty=(Icon:typeof MessageCircle,title:string,description:string)=><Empty className="border-0 px-3 py-9"><EmptyHeader><EmptyMedia variant="icon"><Icon aria-hidden="true"/></EmptyMedia><EmptyTitle>{t(title)}</EmptyTitle><EmptyDescription>{t(description)}</EmptyDescription></EmptyHeader></Empty>;
 const taskRows=(key:string)=>{const items=tasks.filter(task=>key==='chats'?!task.projectId:task.projectId===key);const limit=limits[key]||30;return <SidebarMenu>{items.slice(0,limit).map((task,index)=><SidebarMenuItem key={task.id}>{activeGroup==='chats'&&key==='chats'&&(index===0||dateGroup(items[index-1])!==dateGroup(task))&&<h3 className="nav-date-heading">{t(dateGroup(task))}</h3>}<VirtualBlock enabled={limit>30}>{row(task)}</VirtualBlock></SidebarMenuItem>)}{items.length>limit&&<SidebarMenuItem><Button variant="ghost" onClick={()=>setLimits(old=>({...old,[key]:limit+30}))}>{t('加载更多')} · {items.length-limit}</Button></SidebarMenuItem>}</SidebarMenu>;};
 const [collapsed,setCollapsed]=useState<Set<string>>(new Set());
 const [groups,setGroups]=useState({projects:false,chats:false,extensions:false});
 const previewRef=useRef<HTMLDivElement>(null);
 const [preview,setPreview]=useState<{project:Project;anchor:HTMLElement}|null>(null);
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const cancel=()=>{if(timer.current)clearTimeout(timer.current);};
 const hide=()=>{cancel();setPreview(null);};
 const leave=()=>{cancel();timer.current=setTimeout(()=>{if(!previewRef.current?.contains(document.activeElement))setPreview(null);},220);};
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 const show=(el:HTMLElement,project:Project)=>{hide();timer.current=setTimeout(()=>setPreview({project,anchor:el}),400);};
 const toggleProject=(id:string)=>{hide();setCollapsed(old=>{const next=new Set(old);if(next.has(id))next.delete(id);else next.add(id);return next;});};
 const statusLabel=(task:NavTask)=>task.draft?'草稿':task.queued?'排队中':task.status==='waiting'?(task.questions?.some(q=>q.blocking)?'等待回答':'等待审批'):task.status==='running'?'运行中':task.status==='preparing'?'准备中':task.status==='stopping'?'停止中':task.status==='failed'?'失败':task.status==='interrupted'?'已中断':task.unread?'已完成':'';
 const row=(task:NavTask)=><div className={`tree-task ${selected===task.id?'selected':''}`} key={task.id}><SidebarMenuButton isActive={selected===task.id} className="min-w-0 flex-1 pr-2 group-has-data-[sidebar=menu-action]/menu-item:pr-2 data-active:bg-transparent data-active:hover:bg-transparent data-active:text-inherit" aria-current={selected===task.id?'page':undefined} onClick={()=>open(task)} title={task.title}><span className={`task-state ${task.status}`} aria-label={task.draft?t("草稿"):t(runStatus[task.status as AgentRun['status']])} /><span>{task.title}</span>{task.unread&&<small aria-label={t("未读更新")}>●</small>}{statusLabel(task)&&<small className={`task-status-label ${task.status}`}>{t(statusLabel(task))}</small>}</SidebarMenuButton><span className="tree-row-actions"><SidebarMenuAction className="icon-button row-menu shrink-0 static h-8 w-7 after:inset-0" aria-label={`${t("管理任务：")}${task.title}`} onClick={()=>editTask(task)}><MoreHorizontal size={14}/></SidebarMenuAction></span></div>;
 const heading=(key:'projects'|'chats'|'extensions',label:string,action?:string,add?:()=>void)=>activeGroup?null:<div className="nav-caption caption-action"><SidebarGroupLabel render={<button/>} className="nav-group-toggle w-full" aria-expanded={!!activeGroup||!groups[key]} aria-controls={`nav-${key}`} onClick={()=>{if(activeGroup)return;hide();setGroups({...groups,[key]:!groups[key]});}}>{key==='projects'?<ProjectCategoryIcon/>:key==='chats'?<MessageCircle size={18}/>:<ExtensionCategoryIcon/>}<span>{t(label)}</span>{!activeGroup&&<ChevronRight size={16} style={{transform:groups[key]?undefined:'rotate(90deg)'}}/>}</SidebarGroupLabel>{action&&<SidebarGroupAction className="icon-button nav-group-add static shrink-0" title={t(action)} aria-label={t(action)} onClick={add}>{key==='projects'?<Plus size={18}/>:key==='extensions'?<Settings size={18}/>:<SquarePen size={18}/>}</SidebarGroupAction>}</div>;
 return <SidebarContent ref={contentRef} className="workspace-navigation" onScroll={event=>{hide();scrollPositions.current[activeGroup||'all']=event.currentTarget.scrollTop;}} onKeyDown={e=>{if(e.key==='Escape')hide();}}>
  <SidebarGroup className={activeGroup&&activeGroup!=='projects'?'p-0 hidden':'p-0'} role="region" aria-label={t("我的项目")}>{heading('projects','项目','添加项目',addProject)}<Collapsible open={!!activeGroup||!groups.projects}><CollapsibleContent keepMounted id="nav-projects" inert={!activeGroup&&groups.projects} aria-hidden={!activeGroup&&groups.projects}><SidebarGroupContent>
  {projects.slice(0,projectLimit).map(project=><VirtualBlock key={project.id} enabled={projects.length>30}><SidebarMenu><SidebarMenuItem className="project-tree"><div className={`project-tree-row ${projectId===project.id?'selected':''}`} onMouseEnter={e=>show(e.currentTarget,project)} onMouseLeave={leave} onContextMenu={e=>{e.preventDefault();hide();editProject(project);}}>
   <button className="icon-button tree-toggle" aria-label={`${t(collapsed.has(project.id)?"展开项目：":"折叠项目：")}${project.name}`} aria-expanded={!collapsed.has(project.id)} aria-controls={`project-tasks-${project.id}`} onClick={()=>toggleProject(project.id)}><ChevronRight size={16} style={{transform:collapsed.has(project.id)?undefined:"rotate(90deg)"}}/></button>
   <SidebarMenuButton isActive={projectId===project.id} aria-current={projectId===project.id?'page':undefined} className="project-tree-name min-w-0 flex-1 pr-0 group-has-data-[sidebar=menu-action]/menu-item:pr-0 data-active:bg-transparent data-active:hover:bg-transparent data-active:text-inherit" onClick={()=>openProject(project.id)} onFocus={e=>show(e.currentTarget,project)} onBlur={leave} onKeyDown={e=>{if(e.key==='ArrowRight'&&preview){e.preventDefault();previewRef.current?.querySelector('button')?.focus();}}}><span>{project.name}</span></SidebarMenuButton>
   <span className="tree-row-actions"><SidebarMenuAction className="icon-button row-menu shrink-0 static h-8 w-7 after:inset-0" aria-label={`${t("管理项目：")}${project.name}`} onClick={event=>{event.stopPropagation();hide();editProject(project);}}><MoreHorizontal size={15}/></SidebarMenuAction>
   <SidebarMenuAction className="icon-button row-menu shrink-0 static h-8 w-7 after:inset-0" aria-label={`${t("在项目中新建任务：")}${project.name}`} onClick={event=>{event.stopPropagation();hide();newTask(project.id);}}><SquarePen size={15}/></SidebarMenuAction></span>
  </div><Collapsible open={!collapsed.has(project.id)}><CollapsibleContent id={`project-tasks-${project.id}`} keepMounted inert={collapsed.has(project.id)} aria-hidden={collapsed.has(project.id)}><div><SidebarMenuSub className="project-children ml-5 mr-0 pl-2 pr-0"><li>{taskRows(project.id)}</li></SidebarMenuSub></div></CollapsibleContent></Collapsible></SidebarMenuItem></SidebarMenu></VirtualBlock>)}{projects.length>projectLimit&&<Button variant="ghost" size="sm" onClick={()=>setProjectLimit(n=>n+30)}>{t('加载更多项目')}</Button>}
  {!projects.length&&(activeGroup?empty(Folder,"还没有项目","新建项目，将工作目录和相关任务整理在一起。"): <p className="nav-empty">{t("添加项目，整理相关任务。")}</p>)}</SidebarGroupContent></CollapsibleContent></Collapsible></SidebarGroup>
  <SidebarGroup className={activeGroup&&activeGroup!=='chats'?'p-0 hidden':'p-0'} role="region" aria-label={t("任务")}>{heading('chats','任务','新建任务',()=>newTask())}<Collapsible open={!!activeGroup||!groups.chats}><CollapsibleContent keepMounted id="nav-chats" inert={!activeGroup&&groups.chats} aria-hidden={!activeGroup&&groups.chats}><SidebarGroupContent>{taskRows('chats')}{!tasks.some(t=>!t.projectId)&&(activeGroup?empty(MessageCircle,"还没有独立任务","点击新建任务开始。项目内的任务请在项目中查看。"):<p className="nav-empty">{t("你的任务会显示在这里。")}</p>)}</SidebarGroupContent></CollapsibleContent></Collapsible></SidebarGroup>
  <SidebarGroup className={activeGroup&&activeGroup!=='extensions'?'p-0 hidden':'p-0'} role="region" aria-label={t("扩展")}>{heading('extensions','扩展','管理扩展',manageExtensions)}<Collapsible open={!!activeGroup||!groups.extensions}><CollapsibleContent keepMounted id="nav-extensions" inert={!activeGroup&&groups.extensions} aria-hidden={!activeGroup&&groups.extensions}><SidebarGroupContent>{extensionsContent}{activeGroup&&!hasExtensions&&empty(Settings,"暂无可用扩展","前往管理扩展，安装或启用你需要的扩展。")}</SidebarGroupContent></CollapsibleContent></Collapsible></SidebarGroup>
  {preview&&<Popover open onOpenChange={open=>{if(!open)hide();}}><PopoverContent anchor={preview.anchor} side="right" align="start" sideOffset={12} initialFocus={false} ref={previewRef} role="region" aria-label={t("项目信息")} onMouseEnter={cancel} onMouseLeave={leave} onFocus={cancel} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))hide();}} onKeyDown={e=>{if(e.key==='Escape'){hide();}}}><ProjectInfo name={preview.project.name} path={preview.project.path} count={tasks.filter(t=>t.projectId===preview.project.id).length} edit={()=>{const project=preview.project;hide();editProject(project);}}/></PopoverContent></Popover>}
 </SidebarContent>;
}
